{ ... }:

let
  palette = {
    gruvbox = {
      bg0 = "#282828";
      bg1 = "#3c3836";
      bg2 = "#504945";
      bg4 = "#7c6f64";
      fg0 = "#fbf1c7";
      fg4 = "#a89984";
      red = "#fb4934";
      green = "#b8bb26";
      yellow = "#fabd2f";
      blue = "#83a598";
      purple = "#d3869b";
      aqua = "#8ec07c";
      orange = "#fe8019";
    };
    rose-pine = {
      base = "#191724";
      surface = "#1f1d2e";
      overlay = "#26233a";
      muted = "#6e6a86";
      subtle = "#908caa";
      text = "#e0def4";
      love = "#eb6f92";
      gold = "#f6c177";
      rose = "#ebbcba";
      pine = "#31748f";
      foam = "#9ccfd8";
      iris = "#c4a7e7";
      bg0 = "#191724";
      bg1 = "#1f1d2e";
      bg2 = "#26233a";
      bg4 = "#6e6a86";
      fg0 = "#e0def4";
      fg4 = "#908caa";
      red = "#eb6f92";
      green = "#31748f";
      yellow = "#f6c177";
      blue = "#c4a7e7";
      purple = "#c4a7e7";
      aqua = "#9ccfd8";
      orange = "#f6c177";
      cyan = "#9ccfd8";
      magenta = "#c4a7e7";
    };
    everforest = {
      bg0 = "#2b3339";
      bg1 = "#323c41";
      bg2 = "#3a4248";
      bg4 = "#7a8478";
      fg0 = "#d3c6aa";
      fg4 = "#7a8478";
      red = "#e67e80";
      green = "#a7c080";
      yellow = "#dbbc7f";
      blue = "#7fbbb3";
      purple = "#d699b6";
      aqua = "#83c092";
      orange = "#e69875";
      comment = "#7a8478";
    };
    carbonfox = {
      bg0 = "#161616";
      bg1 = "#262626";
      bg2 = "#393939";
      bg4 = "#525252";
      fg = "#f2f4f8";
      fg0 = "#f2f4f8";
      fg4 = "#525252";
      red = "#ee5396";
      green = "#25be6a";
      yellow = "#08bdba";
      blue = "#78a9ff";
      purple = "#be95ff";
      aqua = "#33b1ff";
      orange = "#ee5396";
      magenta = "#be95ff";
      cyan = "#33b1ff";
      comment = "#525252";
    };
    pastel = {
      bg0 = "#1A1D23";
      bg1 = "#22262E";
      bg2 = "#2A2F38";
      bg4 = "#5C6370";
      fg0 = "#C5CDD9";
      fg4 = "#5C6370";
      red = "#E06C75";
      green = "#98C379";
      yellow = "#E5C07B";
      blue = "#61AFEF";
      purple = "#C678DD";
      aqua = "#56B6C2";
      orange = "#E5C07B";
      magenta = "#C678DD";
      cyan = "#56B6C2";
      comment = "#5C6370";
    };
  };

  mkTheme = name: pal: {
    "ui.background" = { };
    "ui.background.separator" = { fg = pal.bg1; };
    "ui.cursor" = { modifiers = [ "reversed" ]; };
    "ui.cursor.insert" = { modifiers = [ "underlined" ]; };
    "ui.cursor.select" = { modifiers = [ "reversed" ]; };
    "ui.cursor.match" = { fg = pal.yellow; modifiers = [ "underlined" ]; };
    "ui.cursor.primary" = { modifiers = [ "reversed" ]; };
    "ui.gutter" = { bg = pal.bg0; };
    "ui.gutter.selected" = { fg = pal.fg0; bg = pal.bg1; modifiers = [ "bold" ]; };
    "ui.linenr" = { fg = pal.fg4; };
    "ui.linenr.selected" = { fg = pal.fg0; bg = pal.bg1; };
    "ui.selection" = { bg = pal.bg2; };
    "ui.selection.primary" = { bg = pal.blue; fg = pal.bg0; };
    "ui.statusline" = { fg = pal.fg0; bg = pal.bg1; };
    "ui.statusline.inactive" = { fg = pal.fg4; bg = pal.bg0; };
    "ui.statusline.normal" = { fg = pal.bg0; bg = pal.blue; };
    "ui.statusline.insert" = { fg = pal.bg0; bg = pal.green; };
    "ui.statusline.select" = { fg = pal.bg0; bg = pal.purple; };
    "ui.popup" = { fg = pal.fg0; bg = pal.bg1; };
    "ui.popup.info" = { fg = pal.fg0; bg = pal.bg2; };
    "ui.window" = { bg = pal.bg1; };
    "ui.help" = { fg = pal.fg0; bg = pal.bg1; };
    "ui.text" = { fg = pal.fg0; };
    "ui.text.focus" = { fg = pal.fg0; modifiers = [ "bold" ]; };
    "ui.text.info" = { fg = pal.blue; };
    "ui.virtual.ruler" = { bg = pal.bg1; };
    "ui.virtual.whitespace" = { fg = pal.fg4; };
    "ui.virtual.indent-guide" = { fg = pal.bg4; };
    "ui.virtual.wrap" = { fg = pal.fg4; };
    "ui.menu" = { fg = pal.fg0; bg = pal.bg1; };
    "ui.menu.selected" = { fg = pal.bg0; bg = pal.blue; modifiers = [ "bold" ]; };
    "ui.menu.scroll" = { fg = pal.fg4; };
    "warning" = { fg = pal.yellow; };
    "error" = { fg = pal.red; };
    "info" = { fg = pal.blue; };
    "hint" = { fg = pal.aqua; };
    "diagnostic" = { modifiers = [ "underlined" ]; };
    "diagnostic.hint" = { underline = { color = pal.aqua; style = "dashed"; }; };
    "diagnostic.info" = { underline = { color = pal.blue; style = "dashed"; }; };
    "diagnostic.warning" = { underline = { color = pal.yellow; style = "curl"; }; };
    "diagnostic.error" = { underline = { color = pal.red; style = "curl"; }; };
    "variable" = { fg = pal.fg0; };
    "variable.builtin" = { fg = pal.orange; };
    "variable.other.member" = { fg = pal.red; };
    "function" = { fg = pal.blue; };
    "function.builtin" = { fg = pal.blue; };
    "function.macro" = { fg = pal.aqua; };
    "keyword" = { fg = pal.purple; };
    "keyword.control" = { fg = pal.purple; };
    "keyword.directive" = { fg = pal.purple; };
    "keyword.function" = { fg = pal.purple; };
    "operator" = { fg = pal.aqua; };
    "comment" = { fg = pal.fg4; };
    "special" = { fg = pal.aqua; };
    "string" = { fg = pal.green; };
    "string.special" = { fg = pal.aqua; };
    "constant" = { fg = pal.orange; };
    "constant.numeric" = { fg = pal.orange; };
    "constant.character.escape" = { fg = pal.aqua; };
    "type" = { fg = pal.yellow; };
    "type.builtin" = { fg = pal.yellow; };
    "constructor" = { fg = pal.blue; };
    "namespace" = { fg = pal.blue; };
    "label" = { fg = pal.purple; };
    "tag" = { fg = pal.blue; };
    "attribute" = { fg = pal.yellow; };
    "diff.plus" = { fg = pal.green; };
    "diff.minus" = { fg = pal.red; };
    "diff.delta" = { fg = pal.yellow; };
  };

in
{
  programs.helix.themes = {
    pastelglow = mkTheme "pastelglow" palette.pastel;
    gruvbox_dark = mkTheme "gruvbox_dark" palette.gruvbox;
    rose_pine = mkTheme "rose_pine" palette.rose-pine;
    everforest_dark = mkTheme "everforest_dark" palette.everforest;
    carbonfox = mkTheme "carbonfox" palette.carbonfox;
  };
}
