#!/usr/bin/env bash
# Switch Nix theme — kitty, yazi, neovim, hyprland, gtk, fastfetch

THEME="${1:-catppuccin}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

declare -A C
source "$SCRIPT_DIR/themes.conf"

if load_common_palette "$THEME"; then
  :
else
  case "$THEME" in
    everforest)
      C[name]="Everforest Dark"
      C[base]="#2d3b2d" C[mantle]="#283328" C[crust]="#232b23"
      C[surface0]="#374637" C[surface1]="#414f41" C[surface2]="#4a584a"
      C[overlay0]="#6a7b6a" C[overlay1]="#7a8b7a"
      C[text]="#d3c6aa" C[subtext1]="#c9b99a" C[subtext0]="#b9a98a"
      C[red]="#e67e80" C[maroon]="#e67e80" C[rosewater]="#c9b99a" C[flamingo]="#c9b99a"
      C[pink]="#df69ba" C[mauve]="#df69ba" C[lavender]="#7fbbb3"
      C[blue]="#7fbbb3" C[sapphire]="#7fbbb3" C[sky]="#7fbbb3"
      C[teal]="#83c092" C[green]="#a7c080" C[yellow]="#dbbc7f"
      C[peach]="#e69875" C[orange]="#e69875"
      C[accent]="#a7c080"
      C[overlay2]="#8a9b8a"
      ;;
    carbonfox)
      C[name]="Carbonfox"
      C[base]="#161616" C[mantle]="#121212" C[crust]="#121212"
      C[surface0]="#222222" C[surface1]="#2a2a2a" C[surface2]="#525253"
      C[overlay0]="#6e7074" C[overlay1]="#9a9ca0"
      C[text]="#f2f4f8" C[subtext1]="#dfdfe0" C[subtext0]="#b2b4b8"
      C[red]="#ff0000" C[maroon]="#ff0000" C[rosewater]="#dfdfe0" C[flamingo]="#dfdfe0"
      C[pink]="#c6c6c6" C[mauve]="#ffffff" C[lavender]="#c6c6c6"
      C[blue]="#c6c6c6" C[sapphire]="#a0a0a0" C[sky]="#a0a0a0"
      C[teal]="#808080" C[green]="#a0a0a0" C[yellow]="#c6c6c6"
      C[peach]="#a0a0a0" C[orange]="#a0a0a0"
      C[accent]="#ffffff"
      C[overlay2]="#b2b4b8"
      ;;
    *)
      echo "Unknown theme: $THEME" >&2
      exit 1
      ;;
  esac
fi

# Script-specific keys per theme
case "$THEME" in
  catppuccin)
    C[cat_accent]="lavender" C[kitty_theme]="catppuccin-mocha"
    C[gtk_theme]="catppuccin-mocha-lavender-standard" C[gtk_scheme]="prefer-dark"
    C[kvantum_theme]="catppuccin-mocha-lavender" C[wallpaper_dir]="CatppuccinMocha"
    ;;
  rosepine)
    C[cat_accent]="lavender" C[kitty_theme]="rose-pine"
    C[gtk_theme]="catppuccin-mocha-lavender-standard" C[gtk_scheme]="prefer-dark"
    C[kvantum_theme]="rose-pine-iris" C[wallpaper_dir]="RosePine"
    ;;
  gruvbox)
    C[cat_accent]="yellow" C[kitty_theme]="gruvbox-dark"
    C[gtk_theme]="Gruvbox-Dark" C[gtk_scheme]="prefer-dark"
    C[kvantum_theme]="Gruvbox-Dark-Brown" C[wallpaper_dir]="GruvboxDark"
    ;;
  everforest)
    C[cat_accent]="green" C[kitty_theme]="everforest"
    C[gtk_theme]="Gruvbox-Dark" C[gtk_scheme]="prefer-dark"
    C[kvantum_theme]="Gruvbox-Dark-Brown" C[wallpaper_dir]="Everforest"
    ;;
  carbonfox)
    C[cat_accent]="mauve" C[kitty_theme]="carbonfox" C[hypr_accent]="#3a3a3a" C[accent_ui]="#3a3a3a"
    C[gtk_theme]="catppuccin-mocha-lavender-standard" C[gtk_scheme]="prefer-dark"
    C[kvantum_theme]="KvAdaptaDark" C[wallpaper_dir]="Carbonfox"
    ;;
  gruvbox-light)
    C[cat_accent]="yellow" C[kitty_theme]="gruvbox-light"
    C[gtk_theme]="Gruvbox-Light" C[gtk_scheme]="prefer-light"
    C[icon_theme]="Papirus-Light"
    C[kvantum_theme]="Gruvbox-Dark-Brown" C[wallpaper_dir]="GruvboxLight"
    ;;
esac

# ── Kitty ───────────────────────────────────────────────────────────────────
switch_kitty() {
  mkdir -p "$HOME/.config/kitty/themes"
  cat > "$HOME/.config/kitty/themes/current.conf" << EOF
# ${C[name]} — auto-generated by switch-theme.sh
foreground              ${C[text]}
background              ${C[base]}
selection_foreground    ${C[base]}
selection_background    ${C[rosewater]}
cursor                  ${C[rosewater]}
cursor_text_color       ${C[base]}
url_color               ${C[rosewater]}
active_border_color     ${C[lavender]}
inactive_border_color   ${C[overlay0]}
bell_border_color       ${C[yellow]}
wayland_titlebar_color  system
active_tab_foreground   ${C[crust]}
active_tab_background   ${C[mauve]}
inactive_tab_foreground ${C[text]}
inactive_tab_background ${C[mantle]}
tab_bar_background      ${C[crust]}
mark1_foreground ${C[base]}
mark1_background ${C[lavender]}
mark2_foreground ${C[base]}
mark2_background ${C[mauve]}
mark3_foreground ${C[base]}
mark3_background ${C[sapphire]}
color0  ${C[surface1]}
color8  ${C[surface2]}
color1  ${C[red]}
color9  ${C[red]}
color2  ${C[green]}
color10 ${C[green]}
color3  ${C[yellow]}
color11 ${C[yellow]}
color4  ${C[blue]}
color12 ${C[blue]}
color5  ${C[pink]}
color13 ${C[pink]}
color6  ${C[teal]}
color14 ${C[teal]}
color7  ${C[subtext1]}
color15 ${C[subtext0]}
EOF
  kill -SIGUSR1 $(pgrep kitty) 2>/dev/null || true
}

# ── Yazi ────────────────────────────────────────────────────────────────────
gen_yazi_theme() {
  local tmpl="$HOME/.config/quickshell/templates/yazi-theme.toml.tmpl"
  [ -f "$tmpl" ] || return
  mkdir -p "$HOME/.config/yazi"
  sed \
    -e "s/#1e1e2e/${C[base]}/g" \
    -e "s/#181825/${C[mantle]}/g" \
    -e "s/#11111b/${C[crust]}/g" \
    -e "s/#313244/${C[surface0]}/g" \
    -e "s/#45475a/${C[surface1]}/g" \
    -e "s/#585b70/${C[surface2]}/g" \
    -e "s/#6c7086/${C[overlay0]}/g" \
    -e "s/#7f849c/${C[overlay1]}/g" \
    -e "s/#9399b2/${C[overlay2]}/g" \
    -e "s/#cdd6f4/${C[text]}/g" \
    -e "s/#bac2de/${C[subtext1]}/g" \
    -e "s/#a6adc8/${C[subtext0]}/g" \
    -e "s/#f38ba8/${C[red]}/g" \
    -e "s/#eba0ac/${C[maroon]}/g" \
    -e "s/#f5e0dc/${C[rosewater]}/g" \
    -e "s/#f2cdcd/${C[flamingo]}/g" \
    -e "s/#f5c2e7/${C[pink]}/g" \
    -e "s/#cba6f7/${C[mauve]}/g" \
    -e "s/#b4befe/${C[lavender]}/g" \
    -e "s/#89b4fa/${C[blue]}/g" \
    -e "s/#74c7ec/${C[sapphire]}/g" \
    -e "s/#89dceb/${C[sky]}/g" \
    -e "s/#94e2d5/${C[teal]}/g" \
    -e "s/#a6e3a1/${C[green]}/g" \
    -e "s/#f9e2af/${C[yellow]}/g" \
    -e "s/#fab387/${C[peach]}/g" \
    "$tmpl" > "$HOME/.config/yazi/theme.toml"
}

# ── Neovim ──────────────────────────────────────────────────────────────────
nvim_reload() {
  local cs bg
  case "$THEME" in
      catppuccin)    cs="catppuccin" bg="dark"  ;;
    rosepine)      cs="rose-pine"  bg="dark"  ;;
    gruvbox)       cs="gruvbox"    bg="dark"  ;;
    gruvbox-light) cs="gruvbox"    bg="light" ;;
    carbonfox)     cs="carbonfox"  bg="dark"  ;;
    everforest)    cs="everforest" bg="dark"  ;;
  esac
  local uid
  uid=$(id -u)
  for sock in $(find /run/user/"$uid" -maxdepth 3 -name "nvim.*" -type s 2>/dev/null); do
    nvim --server "$sock" \
      --remote-send ":set background=$bg | colorscheme $cs<CR>" \
      2>/dev/null || true
  done
}

# ── GTK ─────────────────────────────────────────────────────────────────────
switch_gtk() {
  local gtk_theme="${C[gtk_theme]}"
  local scheme="${C[gtk_scheme]}"
  local icons="${C[icon_theme]:-Papirus-Dark}"
  local prefer_dark
  prefer_dark=$([ "$scheme" = "prefer-dark" ] && echo 1 || echo 0)

  local nix_share="/run/current-system/sw/share"
  local local_themes="$HOME/.local/share/themes"
  local local_icons="$HOME/.local/share/icons"
  mkdir -p "$local_themes" "$local_icons"

  # Symlink GTK theme
  [ -d "$nix_share/themes/$gtk_theme" ] && [ ! -L "$local_themes/$gtk_theme" ] && \
    ln -sf "$nix_share/themes/$gtk_theme" "$local_themes/$gtk_theme"

  # Symlink icon theme (Papirus-Dark or Papirus-Light)
  [ -d "$nix_share/icons/$icons" ] && [ ! -L "$local_icons/$icons" ] && \
    ln -sf "$nix_share/icons/$icons" "$local_icons/$icons"

  local settings_block
  settings_block="[Settings]
gtk-theme-name=$gtk_theme
gtk-application-prefer-dark-theme=$prefer_dark
gtk-font-name=JetBrainsMono Nerd Font 10
gtk-icon-theme-name=$icons
gtk-cursor-theme-name=phinger-cursors-dark
gtk-cursor-theme-size=24"

  mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
  echo "$settings_block" > "$HOME/.config/gtk-3.0/settings.ini"
  echo "$settings_block" > "$HOME/.config/gtk-4.0/settings.ini"

  # dconf — live reload pour les apps en cours
  if command -v dconf &>/dev/null; then
    dconf write /org/gnome/desktop/interface/gtk-theme      "'$gtk_theme'" 2>/dev/null || true
    dconf write /org/gnome/desktop/interface/color-scheme   "'$scheme'"    2>/dev/null || true
    dconf write /org/gnome/desktop/interface/font-name      "'JetBrainsMono Nerd Font 10'" 2>/dev/null || true
    dconf write /org/gnome/desktop/interface/icon-theme     "'$icons'"     2>/dev/null || true
  fi
}

# ── Btop ────────────────────────────────────────────────────────────────────
gen_btop_theme() {
  local theme_file="$HOME/.config/btop/themes/current.theme"
  mkdir -p "$(dirname "$theme_file")"
  cat > "$theme_file" << EOF
# ${C[name]} — auto-generated by switch-theme.sh
theme[main_bg]="${C[base]}"
theme[main_fg]="${C[text]}"
theme[title]="${C[text]}"
theme[hi_fg]="${C[accent]}"
theme[selected_bg]="${C[surface1]}"
theme[selected_fg]="${C[accent]}"
theme[inactive_fg]="${C[overlay1]}"
theme[graph_text]="${C[accent]}"
theme[meter_bg]="${C[surface1]}"
theme[proc_misc]="${C[rosewater]}"
theme[cpu_box]="${C[accent]}"
theme[mem_box]="${C[accent]}"
theme[net_box]="${C[accent]}"
theme[proc_box]="${C[accent]}"
theme[div_line]="${C[overlay0]}"
theme[temp_start]="${C[green]}"
theme[temp_mid]="${C[yellow]}"
theme[temp_end]="${C[red]}"
theme[cpu_start]="${C[teal]}"
theme[cpu_mid]="${C[sapphire]}"
theme[cpu_end]="${C[accent]}"
theme[free_start]="${C[mauve]}"
theme[free_mid]="${C[lavender]}"
theme[free_end]="${C[blue]}"
theme[cached_start]="${C[sapphire]}"
theme[cached_mid]="${C[blue]}"
theme[cached_end]="${C[accent]}"
theme[available_start]="${C[peach]}"
theme[available_mid]="${C[maroon]}"
theme[available_end]="${C[red]}"
theme[used_start]="${C[green]}"
theme[used_mid]="${C[teal]}"
theme[used_end]="${C[sky]}"
theme[download_start]="${C[peach]}"
theme[download_mid]="${C[maroon]}"
theme[download_end]="${C[red]}"
theme[upload_start]="${C[green]}"
theme[upload_mid]="${C[teal]}"
theme[upload_end]="${C[sky]}"
theme[process_start]="${C[accent]}"
theme[process_mid]="${C[sky]}"
theme[process_end]="${C[mauve]}"
EOF

  local conf="$HOME/.config/btop/btop.conf"
  if [ ! -f "$conf" ]; then
    echo "color_theme = \"$theme_file\"" > "$conf"
  elif grep -q "^color_theme" "$conf"; then
    sed -i "s|^color_theme = .*|color_theme = \"$theme_file\"|" "$conf"
  else
    echo "color_theme = \"$theme_file\"" >> "$conf"
  fi
}

# ── Wallpaper ────────────────────────────────────────────────────────────────
switch_wallpaper() {
  local wp_dir="$HOME/Pictures/Wallpapers/${C[wallpaper_dir]}"
  [ -d "$wp_dir" ] || return
  local wp
  wp=$(find "$wp_dir" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | shuf -n 1)
  [ -n "$wp" ] && awww img "$wp" --transition-type wave --transition-duration 2 2>/dev/null || true
}

# ── Swaync ──────────────────────────────────────────────────────────────────
gen_swaync_style() {
  mkdir -p "$HOME/.config/swaync"
  cat > "$HOME/.config/swaync/style.css" << EOF
/* ${C[name]} — auto-generated by switch-theme.sh */
* {
  all: unset;
  font-size: 14px;
  font-family: "JetBrainsMono Nerd Font";
  transition: 200ms;
}

trough highlight { background: ${C[text]}; }

scale { margin: 0 7px; }

scale trough {
  margin: 0rem 1rem;
  min-height: 8px;
  min-width: 70px;
  border-radius: 12.6px;
}

trough slider {
  margin: -10px;
  border-radius: 12.6px;
  box-shadow: 0 0 2px rgba(0,0,0,0.8);
  transition: all 0.2s ease;
  background-color: ${C[blue]};
}

trough slider:hover {
  box-shadow: 0 0 2px rgba(0,0,0,0.8), 0 0 8px ${C[blue]};
}

trough { background-color: ${C[surface0]}; }

.notification-background {
  box-shadow: 0 0 8px 0 rgba(0,0,0,0.8), inset 0 0 0 1px ${C[surface1]};
  border-radius: 12.6px;
  margin: 18px;
  background: ${C[mantle]};
  color: ${C[text]};
  padding: 0;
}

.notification-background .notification {
  padding: 7px;
  border-radius: 12.6px;
}

.notification-background .notification.critical {
  box-shadow: inset 0 0 7px 0 ${C[red]};
}

.notification .notification-content { margin: 7px; }
.notification .notification-content overlay { margin: 4px; }

.notification-content .summary { color: ${C[text]}; }
.notification-content .time    { color: ${C[subtext0]}; }
.notification-content .body    { color: ${C[subtext1]}; }

.notification > *:last-child > * { min-height: 3.4em; }

.notification-background .close-button {
  margin: 7px;
  padding: 2px;
  border-radius: 6.3px;
  color: ${C[base]};
  background-color: ${C[red]};
}

.notification-background .close-button:hover  { background-color: ${C[maroon]}; }
.notification-background .close-button:active { background-color: ${C[pink]}; }

.notification .notification-action {
  border-radius: 7px;
  color: ${C[text]};
  box-shadow: inset 0 0 0 1px ${C[surface1]};
  margin: 4px;
  padding: 8px;
  background-color: ${C[surface0]};
}

.notification .notification-action:hover  { background-color: ${C[surface1]}; }
.notification .notification-action:active { background-color: ${C[surface2]}; }

.notification.critical progress { background-color: ${C[red]}; }
.notification.low progress,
.notification.normal progress   { background-color: ${C[blue]}; }

.notification progress,
.notification trough,
.notification progressbar {
  border-radius: 12.6px;
  padding: 3px 0;
}

.control-center {
  box-shadow: 0 0 8px 0 rgba(0,0,0,0.8), inset 0 0 0 1px ${C[surface0]};
  border-radius: 12.6px;
  background-color: ${C[base]};
  color: ${C[text]};
  padding: 14px;
}

.control-center .notification-background {
  border-radius: 7px;
  box-shadow: inset 0 0 0 1px ${C[surface1]};
  margin: 4px 10px;
}

.control-center .notification-background .notification {
  border-radius: 7px;
}

.control-center .notification-background .notification.low { opacity: 0.8; }

.control-center .widget-title > label {
  color: ${C[text]};
  font-size: 1.3em;
}

.control-center .widget-title button {
  border-radius: 7px;
  color: ${C[text]};
  background-color: ${C[surface0]};
  box-shadow: inset 0 0 0 1px ${C[surface1]};
  padding: 8px;
}

.control-center .widget-title button:hover  { background-color: ${C[surface1]}; }
.control-center .widget-title button:active { background-color: ${C[surface2]}; }

.control-center .notification-group { margin-top: 10px; }

.control-center .notification-group:focus .notification-background {
  background-color: ${C[surface0]};
}

scrollbar slider { margin: -3px; opacity: 0.8; }
scrollbar trough { margin: 2px 0; }

.widget-dnd {
  margin-top: 5px;
  border-radius: 8px;
  font-size: 1.1rem;
}

.widget-dnd > switch {
  font-size: initial;
  border-radius: 8px;
  background: ${C[surface0]};
  box-shadow: none;
}

.widget-dnd > switch:checked { background: ${C[blue]}; }

.widget-dnd > switch slider {
  background: ${C[surface1]};
  border-radius: 8px;
}

.widget-mpris-player {
  background: ${C[surface0]};
  border-radius: 12.6px;
  color: ${C[text]};
}

.mpris-overlay {
  background-color: ${C[surface0]};
  opacity: 0.9;
  padding: 15px 10px;
}

.widget-mpris-album-art {
  -gtk-icon-size: 100px;
  border-radius: 12.6px;
  margin: 0 10px;
}

.widget-mpris-title    { font-size: 1.2rem; color: ${C[text]}; }
.widget-mpris-subtitle { font-size: 1rem;   color: ${C[subtext1]}; }

.widget-mpris button {
  border-radius: 12.6px;
  color: ${C[text]};
  margin: 0 5px;
  padding: 2px;
}

.widget-mpris button image    { -gtk-icon-size: 1.8rem; }
.widget-mpris button:hover    { background-color: ${C[surface0]}; }
.widget-mpris button:active   { background-color: ${C[surface1]}; }
.widget-mpris button:disabled { opacity: 0.5; }

.widget-volume { padding: 1rem 0; }

.widget-volume label {
  color: ${C[sapphire]};
  padding: 0 1rem;
}

.widget-volume trough highlight   { background: ${C[sapphire]}; }
.widget-backlight trough highlight { background: ${C[yellow]}; }

.widget-backlight label {
  font-size: 1.5rem;
  color: ${C[yellow]};
}

.widget-backlight .KB { padding-bottom: 1rem; }

.image { padding-right: 0.5rem; }
EOF

  swaync-client -rs 2>/dev/null || true
}

# ── Qt (Kvantum + qt5ct/qt6ct) ──────────────────────────────────────────────
switch_qt() {
  local kvantum_theme="${C[kvantum_theme]}"
  local icons="${C[icon_theme]:-Papirus-Dark}"
  local nix_kvantum="/run/current-system/sw/share/Kvantum"
  local local_kvantum="$HOME/.config/Kvantum"

  mkdir -p "$local_kvantum"

  # Find and copy theme from nix store into ~/.config/Kvantum/
  # (NixOS buildEnv doesn't link share/Kvantum/ due to collisions between packages)
  if [ ! -d "$local_kvantum/$kvantum_theme" ]; then
    local theme_src
    theme_src=$(find /nix/store -maxdepth 5 -name "$kvantum_theme" \
      -path "*/Kvantum/*" -type d 2>/dev/null | head -1)
    if [ -n "$theme_src" ]; then
      cp -r "$theme_src" "$local_kvantum/$kvantum_theme"
    fi
  fi

  # Kvantum theme
  cat > "$local_kvantum/kvantum.kvconfig" << EOF
[General]
theme=$kvantum_theme
EOF

  # qt5ct + qt6ct
  local font_str="JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"
  for ct_dir in "$HOME/.config/qt5ct" "$HOME/.config/qt6ct"; do
    mkdir -p "$ct_dir"
    cat > "$ct_dir/$(basename "$ct_dir").conf" << EOF
[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=$icons
standard_dialogs=default
style=kvantum

[Fonts]
fixed="$font_str"
general="$font_str"
EOF
  done
}

# ── Hyprlock theme ──────────────────────────────────────────────────────────
gen_hyprlock_theme() {
  mkdir -p "$HOME/.config/hypr"
  cat > "$HOME/.config/hypr/hyprlock-theme.conf" << EOF
\$hl_background = ${C[base]#\#}
\$hl_surface    = ${C[surface0]#\#}
\$hl_accent     = ${C[accent]#\#}
\$hl_text       = ${C[text]#\#}
\$hl_red        = ${C[red]#\#}
\$hl_yellow     = ${C[yellow]#\#}
EOF
}

# ── Hyprland borders ────────────────────────────────────────────────────────
live_reload() {
  if command -v hyprctl &>/dev/null; then
    local active_hex="${C[hypr_accent]:-${C[accent]}}"
    active_hex="${active_hex#\#}"
    local inactive_hex="${C[surface0]#\#}"
    hyprctl keyword general:col.active_border "rgba(${active_hex}ff)" 2>/dev/null || true
    hyprctl keyword general:col.inactive_border "rgba(${inactive_hex}ff)" 2>/dev/null || true
  fi
}

# ── Fastfetch ───────────────────────────────────────────────────────────────
gen_fastfetch_config() {
  local cfg="$HOME/.config/fastfetch/config.jsonc"
  [ -f "$cfg" ] || return

  local hex="${C[accent]#\#}"
  local r=$((16#${hex:0:2}))
  local g=$((16#${hex:2:2}))
  local b=$((16#${hex:4:2}))
  local rgb="${r};${g};${b}"

  local dark_accent
  dark_accent=$(printf "#%02x%02x%02x" $((r * 65 / 100)) $((g * 65 / 100)) $((b * 65 / 100)))

  sed -i \
    -e "s/\"1\": \"#[0-9A-Fa-f]\{6\}\"/\"1\": \"${dark_accent}\"/g" \
    -e "s/\"2\": \"#[0-9A-Fa-f]\{6\}\"/\"2\": \"${C[accent]}\"/g" \
    -e "s/\"3\": \"#[0-9A-Fa-f]\{6\}\"/\"3\": \"${dark_accent}\"/g" \
    -e "s/\"4\": \"#[0-9A-Fa-f]\{6\}\"/\"4\": \"${C[accent]}\"/g" \
    -e "s/\"5\": \"#[0-9A-Fa-f]\{6\}\"/\"5\": \"${dark_accent}\"/g" \
    -e "s/\"6\": \"#[0-9A-Fa-f]\{6\}\"/\"6\": \"${C[accent]}\"/g" \
    -e "s/\\\\u001b\\[38;2;[0-9]\\+;[0-9]\\+;[0-9]\\+m/\\\\u001b[38;2;${rgb}m/g" \
    "$cfg"
}

# ── Cider ───────────────────────────────────────────────────────────────────
switch_cider() {
  local theme_dir="$HOME/.config/sh.cider.genten/themes/quickshell"
  mkdir -p "$theme_dir"

  cat > "$theme_dir/theme.yml" << EOF
name: Quickshell Theme
author: quickshell
stylesheets:
  - name: ${C[name]}
    file: quickshell.scss
    description: Auto-generated by switch-theme.sh
version: "1.0"
EOF

  cat > "$theme_dir/quickshell.scss" << EOF
body.body--dark {
  --accent:   ${C[accent_ui]:-${C[accent]}};
  --text:     ${C[text]};
  --subtext1: ${C[subtext1]};
  --subtext0: ${C[subtext0]};
  --overlay1: ${C[overlay1]};
  --overlay0: ${C[overlay0]};
  --surface0: ${C[surface0]};
  --base:     ${C[base]};
  --mantle:   ${C[mantle]};
  --crust:    ${C[crust]};

  --selection-bg: ${C[accent_ui]:-${C[accent]}}4d;
  --red:   ${C[red]};
  --green: ${C[green]};
  --blue:  ${C[blue]};

  background: var(--crust);
  color: var(--text);
  --textDefault: var(--text);
  --systemPrimary: var(--text);
  --systemSecondary: var(--text);
  --systemTertiary: var(--surface0);
  --systemQuinary: var(--selection-bg);
  --systemQuaternary: var(--selection-bg);
  --keyColor: var(--accent);
  --musicKeyColor: var(--accent);
  --tracklistAltRowColor: transparent;
  --vibrantDivider: var(--surface0);
  --q-primary: var(--accent);
  --q-info: var(--blue);
}
EOF
}

# ── Vesktop ─────────────────────────────────────────────────────────────────
switch_vesktop() {
  local theme_file="$HOME/.config/vesktop/themes/quickshell-theme.css"
  mkdir -p "$(dirname "$theme_file")"
  cat > "$theme_file" << EOF
/**
 * @name quickshell-theme
 * @description ${C[name]} — auto-generated by switch-theme.sh
 * @author quickshell
 * @version 1.0.0
 */

:root,
.theme-dark,
.theme-light {
  /* === Backgrounds (new Discord variable names) === */
  --app-frame-background:           ${C[crust]};
  --background-base-lowest:         ${C[crust]};
  --background-base-lower:          ${C[mantle]};
  --background-base-low:            ${C[mantle]};
  --background-surface-high:        ${C[base]};
  --background-surface-higher:      ${C[surface0]};
  --background-accent:              ${C[surface1]};
  --chat-background:                ${C[base]};
  --home-background:                ${C[base]};
  --modal-background:               ${C[base]};
  --channeltextarea-background:      ${C[mantle]};
  --input-background-default:        ${C[crust]};
  --input-text-default:              ${C[text]};
  --input-placeholder-text-default:  ${C[subtext1]};
  --input-border-default:            ${C[overlay0]};
  --custom-status-bubble-background: ${C[crust]};
  --border-normal:                   ${C[surface0]};
  --border-faint:                    ${C[surface0]}60;
  --channel-icon:                    ${C[overlay1]};
  --interactive-background-selected: ${C[surface0]}60;
  --interactive-background-active:   ${C[surface0]}40;

  /* === Text (new names) === */
  --text-default:                  ${C[text]};
  --text-muted:                    ${C[subtext0]};
  --text-subtle:                   ${C[subtext1]};
  --text-link:                     ${C[blue]};
  --text-positive:                 ${C[green]};
  --text-warning:                  ${C[yellow]};
  --text-danger:                   ${C[red]};
  --text-brand:                    ${C[accent]};

  /* === Interactive === */
  --interactive-text-default:      ${C[text]};
  --interactive-background-hover:  ${C[surface0]}60;
  --channels-default:              ${C[overlay1]};
  --icon-muted:                    ${C[overlay1]};

  /* === Brand / Accent === */
  --brand-500:                     ${C[accent]};
  --brand-560:                     ${C[accent]};
  --brand-600:                     ${C[accent]};
  --brand-700:                     ${C[mauve]};
  --control-primary-background-default: ${C[accent]};
  --control-secondary-background-default: ${C[surface1]};
  --logo-primary:                  ${C[accent]};

  /* === Scrollbar === */
  --scrollbar-thin-thumb:          ${C[surface1]};
  --scrollbar-auto-thumb:          ${C[surface1]};
  --scrollbar-auto-track:          ${C[mantle]};

  /* === Brand spectrum (covers selected home button) === */
  --brand-100: ${C[surface0]};
  --brand-200: ${C[surface0]};
  --brand-300: ${C[surface1]};
  --brand-360: ${C[surface2]};
  --brand-400: ${C[overlay0]};
  --brand-430: ${C[overlay0]};
  --brand-460: ${C[overlay1]};
  --brand-500: ${C[accent]};
  --brand-530: ${C[accent]};
  --brand-560: ${C[accent]};
  --brand-600: ${C[accent]};
  --brand-630: ${C[mauve]};
  --brand-660: ${C[mauve]};
  --brand-700: ${C[mauve]};
  --brand-800: ${C[mauve]};
  --brand-900: ${C[base]};

  /* === Missing backgrounds === */
  --background-surface-highest:    ${C[surface1]} !important;
  --bg-surface-raised:             ${C[mantle]};
  --background-gradient-highest:   ${C[mantle]};
  --chat-background-default:       ${C[base]};
  --chat-border:                   ${C[crust]};
  --__header-bar-background:       ${C[mantle]} !important;
  --custom-channel-members-bg:     ${C[mantle]};
  --card-background-default:       ${C[surface0]} !important;
  --modal-footer-background:       ${C[base]};
  --user-profile-overlay-background: ${C[mantle]};
  --background-secondary-alt:      ${C[mantle]} !important;
  --background-mod-subtle:         ${C[surface0]}40 !important;
  --background-mod-strong:         ${C[surface1]}72 !important;

  /* === Legacy variables (older Discord/Vencord) === */
  --background-primary:            ${C[base]};
  --background-secondary:          ${C[mantle]};
  --background-tertiary:           ${C[crust]};
  --background-floating:           ${C[mantle]};
  --background-modifier-hover:     ${C[surface0]}60;
  --background-modifier-active:    ${C[surface1]}80;
  --background-modifier-selected:  ${C[surface1]}60;
  --text-normal:                   ${C[text]};
  --header-primary:                ${C[text]};
  --header-secondary:              ${C[subtext1]};
  --interactive-normal:            ${C[subtext1]};
  --interactive-hover:             ${C[text]};
  --interactive-active:            ${C[accent]};
  --interactive-muted:             ${C[overlay1]};
  --focus-primary:                 ${C[accent]};
  --brand-experiment:              ${C[accent]};
  --brand-experiment-560:          ${C[accent]};
}

/* Fix Discord home button selected state (SVG circle) */
.visual-refresh.theme-dark svg[class^=selectedIcon_]>circle[fill=white],
.visual-refresh .theme-dark svg[class^=selectedIcon_]>circle[fill=white],
svg[class^=selectedIcon_]>circle[fill=white] {
  fill: ${C[crust]};
}
EOF
}

# ── Steam (Millennium Quick CSS) ─────────────────────────────────────────────
switch_steam() {
  local quickcss="$HOME/.config/millennium/quickcss.css"
  [ -f "$quickcss" ] || return

  cat > "$quickcss" << EOF
/* Quickshell theme — auto-generated by switch-theme.sh */
:root {
    --color-light:   ${C[surface1]} !important;
    --color-dark:    ${C[mantle]}   !important;
    --color-darker:  ${C[base]}     !important;
    --color-darkest: ${C[crust]}    !important;
    --scrollbar:     ${C[surface1]} !important;
    --black:         ${C[crust]}    !important;
    --black-ish:     ${C[crust]}    !important;
    --realblack:     ${C[crust]}    !important;
    --blacker-ish:   ${C[crust]}    !important;
    --blacker:       ${C[crust]}    !important;
    --lightblack:    ${C[crust]}    !important;
    --darkergrey:    ${C[crust]}    !important;
    --bedarkgrey:    ${C[crust]}    !important;
    --thegrey:       ${C[mantle]}   !important;
    --begrey:        ${C[surface0]} !important;
    --littlegrey:    ${C[surface0]} !important;
    --darkgrey:      ${C[base]}     !important;
    --grey:          ${C[surface0]} !important;
    --lightgrey:     ${C[surface1]} !important;
    --lightergrey:   ${C[surface0]} !important;
    --grey-ish:      ${C[surface2]} !important;
    --darkerwhite:   ${C[subtext0]} !important;
    --darkwhite:     ${C[subtext1]} !important;
    --white:         ${C[text]}     !important;
    --ingame:        ${C[green]}    !important;
    --online:        ${C[teal]}     !important;
    --offline:       ${C[overlay0]} !important;
}
EOF
}

# ── OBS Studio ──────────────────────────────────────────────────────────────
switch_obs() {
  local theme_dir="$HOME/.config/obs-studio/themes"
  local theme_file="$theme_dir/Quickshell.obt"
  local user_ini="$HOME/.config/obs-studio/user.ini"
  mkdir -p "$theme_dir"

  local is_dark
  is_dark=$([ "$THEME" = "gruvbox-light" ] && echo "false" || echo "true")

  cat > "$theme_file" << EOF
@OBSThemeMeta {
    name: 'Quickshell';
    id: 'io.github.quickshell';
    extends: 'com.obsproject.Yami';
    author: 'quickshell';
    dark: '$is_dark';
}

@OBSThemeVars {
    --bg_window: ${C[mantle]};
    --bg_base: ${C[base]};
    --bg_preview: ${C[crust]};

    --primary: ${C[accent_ui]:-${C[accent]}};
    --primary_light: ${C[blue]};
    --primary_lighter: ${C[sky]};
    --primary_dark: ${C[accent_ui]:-${C[accent]}};
    --primary_darker: ${C[mauve]};

    --warning: ${C[yellow]};
    --danger: ${C[red]};

    --text: ${C[text]};
    --text_light: ${C[subtext1]};
    --text_muted: ${C[subtext0]};
    --text_disabled: ${C[overlay0]};
    --text_inactive: ${C[text]};

    --input_bg: ${C[surface0]};
    --input_bg_hover: ${C[surface1]};
    --input_bg_focus: ${C[surface0]};
    --input_border: ${C[overlay0]};
    --input_border_hover: ${C[overlay1]};
    --input_border_focus: ${C[accent_ui]:-${C[accent]}};

    --border_color: ${C[surface1]};

    --button_bg: ${C[surface0]};
    --button_bg_hover: ${C[surface1]};
    --button_bg_down: ${C[surface2]};
    --button_bg_disabled: ${C[mantle]};
    --button_border: ${C[surface0]};
    --button_border_hover: ${C[overlay0]};
    --button_border_focus: ${C[overlay0]};

    --scrollbar_handle: ${C[surface1]};
    --scrollbar_bg: ${C[base]};
    --scrollbar_hover: ${C[surface2]};
    --scrollbar_down: ${C[overlay0]};
    --scrollbar_border: ${C[surface1]};

    --tab_bg: ${C[mantle]};
    --tab_bg_hover: ${C[surface0]};
    --tab_bg_down: ${C[accent_ui]:-${C[accent]}};
    --tab_bg_disabled: ${C[mantle]};
    --tab_border: ${C[surface1]};
    --tab_border_hover: ${C[overlay0]};
    --tab_border_focus: ${C[accent_ui]:-${C[accent]}};
    --tab_border_selected: ${C[accent_ui]:-${C[accent]}};
}
EOF

  if [ -f "$user_ini" ]; then
    if grep -q "^Theme=" "$user_ini"; then
      sed -i "s|^Theme=.*|Theme=io.github.quickshell|" "$user_ini"
    else
      sed -i '/^\[Appearance\]/a Theme=io.github.quickshell' "$user_ini"
    fi
  fi
}


# ── Firefox ──────────────────────────────────────────────────────────────────
switch_firefox() {
  local profile_dir="$HOME/.config/mozilla/firefox/oracgdsh.default"
  local chrome_dir="$profile_dir/chrome"
  local user_js="$profile_dir/user.js"
  local user_chrome="$chrome_dir/userChrome.css"
  local user_content="$chrome_dir/userContent.css"

  mkdir -p "$chrome_dir"

  local dark_mode
  case "${C[gtk_scheme]}" in
    prefer-light) dark_mode=0 ;;
    *)            dark_mode=1 ;;
  esac

  {
    echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'
    echo "user_pref(\"ui.systemUsesDarkTheme\", ${dark_mode});"
  } > "$user_js"

  cat > "$user_chrome" << EOF
/* Quickshell theme - auto-generated, do not edit */
:root {
  --toolbox-bgcolor-inactive:     ${C[mantle]} !important;
  --toolbarbutton-icon-fill:      ${C[accent]} !important;
  --lwt-text-color:               ${C[text]} !important;
  --toolbar-field-color:          ${C[text]} !important;
  --tab-selected-textcolor:       ${C[text]} !important;
  --toolbar-field-focus-color:    ${C[text]} !important;
  --toolbar-color:                ${C[text]} !important;
  --newtab-text-primary-color:    ${C[text]} !important;
  --arrowpanel-color:             ${C[text]} !important;
  --arrowpanel-background:        ${C[base]} !important;
  --sidebar-text-color:           ${C[text]} !important;
  --lwt-sidebar-text-color:       ${C[text]} !important;
  --lwt-sidebar-background-color: ${C[crust]} !important;
  --toolbar-bgcolor:              ${C[surface0]} !important;
  --newtab-background-color:      ${C[base]} !important;
}

#permissions-granted-icon {
  color: ${C[mantle]} !important;
}

.sidebar-placesTree {
  background-color: ${C[base]} !important;
}

#TabsToolbar {
  background-color: ${C[mantle]} !important;
  color: ${C[text]} !important;
}

#TabsToolbar * {
  color: ${C[text]} !important;
}

hbox#titlebar {
  background-color: ${C[mantle]} !important;
  color: ${C[text]} !important;
}

.urlbar-background {
  background-color: ${C[base]} !important;
}

.urlbarView-url {
  color: ${C[accent]} !important;
}
EOF

  cat > "$user_content" << EOF
/* Quickshell theme - auto-generated, do not edit */
@-moz-document url-prefix("about:") {
  :root {
    --in-content-page-color:      ${C[text]} !important;
    --color-accent-primary:       ${C[accent]} !important;
    --color-accent-primary-hover: ${C[blue]} !important;
    background-color:             ${C[base]} !important;
    --in-content-page-background: ${C[base]} !important;
  }
}

@-moz-document url("about:newtab"), url("about:home") {
  :root {
    --newtab-background-color:           ${C[base]} !important;
    --newtab-background-color-secondary: ${C[surface0]} !important;
    --newtab-element-hover-color:        ${C[surface0]} !important;
    --newtab-text-primary-color:         ${C[text]} !important;
    --newtab-wordmark-color:             ${C[text]} !important;
    --newtab-primary-action-background:  ${C[accent]} !important;
  }
}

@-moz-document url-prefix("about:preferences") {
  :root {
    --in-content-text-color:     ${C[text]} !important;
    --link-color:                ${C[accent]} !important;
    --link-color-hover:          ${C[blue]} !important;
    --in-content-box-background: ${C[surface0]} !important;
  }

  .main-content {
    background-color: ${C[crust]} !important;
  }
}
EOF
}

# ── Userstyles (Stylus via userContent.css + Helium file-watch) ─────────────
gen_userstyles() {
  local cache_dir="$HOME/.config/quickshell/scripts/userstyles-cache"
  local compile_js="$HOME/.config/quickshell/scripts/compile-userstyle.js"
  local user_content="$HOME/.config/mozilla/firefox/oracgdsh.default/chrome/userContent.css"
  local helium_css="$HOME/.config/quickshell/scripts/helium-userstyles.user.css"

  local palette
  palette=$(printf '{
    "rosewater":"%s","flamingo":"%s","pink":"%s","mauve":"%s",
    "red":"%s","maroon":"%s","peach":"%s","yellow":"%s",
    "green":"%s","teal":"%s","sky":"%s","sapphire":"%s",
    "blue":"%s","lavender":"%s","text":"%s","subtext1":"%s",
    "subtext0":"%s","overlay2":"%s","overlay1":"%s","overlay0":"%s",
    "surface2":"%s","surface1":"%s","surface0":"%s",
    "base":"%s","mantle":"%s","crust":"%s","accentColor":"%s"
  }' \
    "${C[rosewater]}" "${C[flamingo]}" "${C[pink]}"     "${C[mauve]}"   \
    "${C[red]}"       "${C[maroon]}"   "${C[peach]}"    "${C[yellow]}"  \
    "${C[green]}"     "${C[teal]}"     "${C[sky]}"      "${C[sapphire]}"\
    "${C[blue]}"      "${C[lavender]}" "${C[text]}"     "${C[subtext1]}"\
    "${C[subtext0]}"  "${C[overlay2]}" "${C[overlay1]}" "${C[overlay0]}"\
    "${C[surface2]}"  "${C[surface1]}" "${C[surface0]}"                 \
    "${C[base]}"      "${C[mantle]}"   "${C[crust]}"    "${C[cat_accent]}")

  # Start with the about: rules already in userContent.css (everything before userstyles block)
  # then append compiled site CSS
  local tmp helium_tmp
  tmp=$(mktemp)
  helium_tmp=$(mktemp)
  trap 'rm -f "$tmp" "$helium_tmp"' EXIT

  # Keep the existing about: page rules
  sed '/^\/\* --- userstyles ---/,$d' "$user_content" > "$tmp" 2>/dev/null || cp "$user_content" "$tmp"
  echo "/* --- userstyles --- */" >> "$tmp"

  # Helium header — UserCSS format so Stylus can install/auto-update it
  local version
  version=$(date +%Y%m%d%H%M%S)
  cat > "$helium_tmp" << EOF
/* ==UserStyle==
@name         Quickshell Theme
@namespace    quickshell.helium
@version      ${version}
@description  Auto-generated by switch-theme.sh — do not edit
==/UserStyle== */
EOF

  local sites=(youtube twitch twitter instagram reddit github codeberg proton claude anilist duckduckgo wikipedia)
  for site in "${sites[@]}"; do
    local less_file="$cache_dir/$site.user.less"
    [ -f "$less_file" ] || continue
    local compiled
    compiled=$(node "$compile_js" "$less_file" "$palette" 2>/dev/null) || continue
    echo "/* == $site == */" | tee -a "$tmp" >> "$helium_tmp"
    printf '%s\n' "$compiled" | tee -a "$tmp" >> "$helium_tmp"
  done

  mv "$tmp" "$user_content"
  mv "$helium_tmp" "$helium_css"
}

# ── Jellyfin ────────────────────────────────────────────────────────────────
switch_jellyfin() {
  local conf="$HOME/.config/jellyfin-theme.conf"
  [ -f "$conf" ] || return 0
  source "$conf"
  [ -n "$JELLYFIN_URL" ] && [ -n "$JELLYFIN_API_KEY" ] || return 0

  local css
  case "$THEME" in
    catppuccin)
      css="@import url('https://jellyfin.catppuccin.com/theme.css');
@import url('https://jellyfin.catppuccin.com/catppuccin-mocha.css');
:root { --main-color: var(--lavender); }" ;;
    gruvbox-light)
      css="@import url('https://jellyfin.catppuccin.com/theme.css');
@import url('https://jellyfin.catppuccin.com/catppuccin-latte.css');
:root { --main-color: var(--yellow); }" ;;
    *)
      css="@import url('https://jellyfin.catppuccin.com/theme.css');
:root {
    --main-color: ${C[accent]};
    --main-background: ${C[base]};
    --main-background-transparent: ${C[base]}dd;
    --dark-background: ${C[crust]};
    --second-background: ${C[mantle]};
    --hover-background: ${C[surface0]};
    --main-text: ${C[text]};
    --white-text: ${C[text]};
    --dimmer-text: ${C[overlay1]};
    --red-color: ${C[red]};
    --green-color: ${C[green]};
    --yellow-color: ${C[yellow]};
}" ;;
  esac

  local css_escaped
  css_escaped=$(printf '%s' "$css" | sed 's/\\/\\\\/g; s/"/\\"/g; s/$/\\n/' | tr -d '\n' | sed 's/\\n$//')
  local payload="{\"CustomCss\":\"${css_escaped}\",\"LoginDisclaimer\":null,\"SplashscreenEnabled\":false}"

  curl -sf -X POST \
    -H "X-Emby-Token: $JELLYFIN_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$payload" \
    "$JELLYFIN_URL/System/Configuration/Branding" > /dev/null
}

# ── Main ────────────────────────────────────────────────────────────────────
switch_kitty
gen_btop_theme
gen_yazi_theme
gen_swaync_style
nvim_reload
switch_gtk
switch_qt
live_reload
switch_wallpaper
gen_fastfetch_config
switch_cider
switch_vesktop
switch_steam
switch_obs
switch_firefox
gen_userstyles
switch_jellyfin
gen_hyprlock_theme

echo "Switched theme to: ${C[name]}"
