#!/usr/bin/env bash
# Switch Nix theme — kitty, yazi, neovim, hyprland, gtk, fastfetch

THEME="${1:-pastelglow}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

declare -A C
source "$SCRIPT_DIR/themes.conf"

if load_common_palette "$THEME"; then
  :
else
  case "$THEME" in
    carbonfox)
      C[name]="Carbonfox"
      C[base]="#161616" C[mantle]="#121212" C[crust]="#121212"
      C[surface0]="#222222" C[surface1]="#2a2a2a" C[surface2]="#525253"
      C[overlay0]="#6e7074" C[overlay1]="#9a9ca0"
      C[text]="#f2f4f8" C[subtext1]="#dfdfe0" C[subtext0]="#b2b4b8"
      C[red]="#ff0000" C[maroon]="#ff0000" C[rosewater]="#dfdfe0" C[flamingo]="#dfdfe0"
      C[pink]="#c6c6c6" C[mauve]="#ffffff" C[lavender]="#c6c6c6"
      C[blue]="#c6c6c6" C[sapphire]="#a0a0a0" C[sky]="#a0a0a0"
      C[teal]="#808080" C[green]="#a0a0a0" C[yellow]="#c6c6c6"
      C[peach]="#a0a0a0" C[orange]="#a0a0a0"
      C[accent]="#ffffff"
      C[overlay2]="#b2b4b8"
      ;;
    *)
      echo "Unknown theme: $THEME" >&2
      exit 1
      ;;
  esac
fi

# Script-specific keys per theme
case "$THEME" in
  pastelglow)
    C[cat_accent]="pink" C[kitty_theme]="pastelglow"
    C[gtk_theme]="Gruvbox-Light" C[gtk_scheme]="prefer-light"
    C[icon_theme]="Papirus-Light"
    C[wallpaper_dir]="PastelGlow"
    ;;
  rosepine)
    C[cat_accent]="lavender" C[kitty_theme]="rose-pine"
    C[gtk_theme]="catppuccin-mocha-lavender-standard" C[gtk_scheme]="prefer-dark"
    C[wallpaper_dir]="RosePine"
    ;;
  gruvbox)
    C[cat_accent]="yellow" C[kitty_theme]="gruvbox-dark"
    C[gtk_theme]="Gruvbox-Dark" C[gtk_scheme]="prefer-dark"
    C[wallpaper_dir]="GruvboxDark"
    ;;
  everforest)
    C[cat_accent]="green" C[kitty_theme]="everforest-dark"
    C[gtk_theme]="adw-gtk3-dark" C[gtk_scheme]="prefer-dark"
    C[wallpaper_dir]="Everforest"
    ;;
  carbonfox)
    C[cat_accent]="mauve" C[kitty_theme]="carbonfox" C[hypr_accent]="#3a3a3a" C[accent_ui]="#3a3a3a"
    C[gtk_theme]="catppuccin-mocha-lavender-standard" C[gtk_scheme]="prefer-dark"
    C[wallpaper_dir]="Carbonfox"
    ;;
  gruvbox-light)
    C[cat_accent]="yellow" C[kitty_theme]="gruvbox-light"
    C[gtk_theme]="Gruvbox-Light" C[gtk_scheme]="prefer-light"
    C[icon_theme]="Papirus-Light"
    C[wallpaper_dir]="GruvboxLight"
    ;;
esac

# ── Kitty ───────────────────────────────────────────────────────────────────
switch_kitty() {
  mkdir -p "$HOME/.config/kitty/themes"
  cat > "$HOME/.config/kitty/themes/current.conf" << EOF
# ${C[name]} — auto-generated by switch-theme.sh
foreground              ${C[text]}
background              ${C[base]}
selection_foreground    ${C[base]}
selection_background    ${C[rosewater]}
cursor                  ${C[rosewater]}
cursor_text_color       ${C[base]}
url_color               ${C[rosewater]}
active_border_color     ${C[lavender]}
inactive_border_color   ${C[overlay0]}
bell_border_color       ${C[yellow]}
wayland_titlebar_color  system
active_tab_foreground   ${C[crust]}
active_tab_background   ${C[mauve]}
inactive_tab_foreground ${C[text]}
inactive_tab_background ${C[mantle]}
tab_bar_background      ${C[crust]}
mark1_foreground ${C[base]}
mark1_background ${C[lavender]}
mark2_foreground ${C[base]}
mark2_background ${C[mauve]}
mark3_foreground ${C[base]}
mark3_background ${C[sapphire]}
color0  ${C[surface1]}
color8  ${C[surface2]}
color1  ${C[red]}
color9  ${C[red]}
color2  ${C[green]}
color10 ${C[green]}
color3  ${C[yellow]}
color11 ${C[yellow]}
color4  ${C[blue]}
color12 ${C[blue]}
color5  ${C[pink]}
color13 ${C[pink]}
color6  ${C[teal]}
color14 ${C[teal]}
color7  ${C[subtext1]}
color15 ${C[subtext0]}
EOF
  kill -SIGUSR1 $(pgrep kitty) 2>/dev/null || true
}

# ── Yazi ────────────────────────────────────────────────────────────────────
gen_yazi_theme() {
  local tmpl="$HOME/.config/quickshell/templates/yazi-theme.toml.tmpl"
  [ -f "$tmpl" ] || return
  mkdir -p "$HOME/.config/yazi"
  sed \
    -e "s/#1e1e2e/${C[base]}/g" \
    -e "s/#181825/${C[mantle]}/g" \
    -e "s/#11111b/${C[crust]}/g" \
    -e "s/#313244/${C[surface0]}/g" \
    -e "s/#45475a/${C[surface1]}/g" \
    -e "s/#585b70/${C[surface2]}/g" \
    -e "s/#6c7086/${C[overlay0]}/g" \
    -e "s/#7f849c/${C[overlay1]}/g" \
    -e "s/#9399b2/${C[overlay2]}/g" \
    -e "s/#cdd6f4/${C[text]}/g" \
    -e "s/#bac2de/${C[subtext1]}/g" \
    -e "s/#a6adc8/${C[subtext0]}/g" \
    -e "s/#f38ba8/${C[red]}/g" \
    -e "s/#eba0ac/${C[maroon]}/g" \
    -e "s/#f5e0dc/${C[rosewater]}/g" \
    -e "s/#f2cdcd/${C[flamingo]}/g" \
    -e "s/#f5c2e7/${C[pink]}/g" \
    -e "s/#cba6f7/${C[mauve]}/g" \
    -e "s/#b4befe/${C[lavender]}/g" \
    -e "s/#89b4fa/${C[blue]}/g" \
    -e "s/#74c7ec/${C[sapphire]}/g" \
    -e "s/#89dceb/${C[sky]}/g" \
    -e "s/#94e2d5/${C[teal]}/g" \
    -e "s/#a6e3a1/${C[green]}/g" \
    -e "s/#f9e2af/${C[yellow]}/g" \
    -e "s/#fab387/${C[peach]}/g" \
    "$tmpl" > "$HOME/.config/yazi/theme.toml"
}

# ── Neovim ──────────────────────────────────────────────────────────────────
nvim_reload() {
  local cs bg
  case "$THEME" in
      pastelglow)    cs="pastelglow" bg="light" ;;
    rosepine)      cs="rose-pine"  bg="dark"  ;;
    gruvbox)       cs="gruvbox"    bg="dark"  ;;
    gruvbox-light) cs="gruvbox"    bg="light" ;;
    carbonfox)     cs="carbonfox"  bg="dark"  ;;
    everforest) cs="everforest" bg="dark" ;;
  esac
  local uid
  uid=$(id -u)
  for sock in $(find /run/user/"$uid" -maxdepth 3 -name "nvim.*" -type s 2>/dev/null); do
    nvim --server "$sock" \
      --remote-send ":set background=$bg | colorscheme $cs<CR>" \
      2>/dev/null || true
  done
}

# ── GTK ─────────────────────────────────────────────────────────────────────
switch_gtk() {
  local scheme="${C[gtk_scheme]}"
  local icons="${C[icon_theme]:-Papirus-Dark}"
  local prefer_dark
  prefer_dark=$([ "$scheme" = "prefer-dark" ] && echo 1 || echo 0)

  mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"

  local gtk_base_theme
  [ "$scheme" = "prefer-light" ] && gtk_base_theme="adw-gtk3" || gtk_base_theme="adw-gtk3-dark"

  local settings_block="[Settings]
gtk-theme-name=$gtk_base_theme
gtk-application-prefer-dark-theme=$prefer_dark
gtk-font-name=JetBrainsMono Nerd Font 10
gtk-icon-theme-name=$icons
gtk-cursor-theme-name=phinger-cursors-dark
gtk-cursor-theme-size=24"

  echo "$settings_block" > "$HOME/.config/gtk-3.0/settings.ini"
  echo "$settings_block" > "$HOME/.config/gtk-4.0/settings.ini"

  # Shared color overrides — adw-gtk3 and libadwaita use the same variables
  local gtk_css
  gtk_css=$(cat << EOF
@define-color accent_color ${C[accent]};
@define-color accent_bg_color ${C[accent]};
@define-color accent_fg_color ${C[base]};
@define-color destructive_color ${C[red]};
@define-color destructive_bg_color ${C[red]};
@define-color destructive_fg_color ${C[base]};
@define-color success_color ${C[green]};
@define-color success_bg_color ${C[green]};
@define-color success_fg_color ${C[base]};
@define-color warning_color ${C[yellow]};
@define-color warning_bg_color ${C[yellow]};
@define-color warning_fg_color ${C[base]};
@define-color error_color ${C[red]};
@define-color error_bg_color ${C[red]};
@define-color error_fg_color ${C[base]};
@define-color window_bg_color ${C[base]};
@define-color window_fg_color ${C[text]};
@define-color view_bg_color ${C[mantle]};
@define-color view_fg_color ${C[text]};
@define-color headerbar_bg_color ${C[crust]};
@define-color headerbar_fg_color ${C[text]};
@define-color headerbar_border_color ${C[surface0]};
@define-color headerbar_backdrop_color ${C[mantle]};
@define-color headerbar_shade_color ${C[crust]};
@define-color card_bg_color ${C[surface0]};
@define-color card_fg_color ${C[text]};
@define-color card_shade_color ${C[crust]};
@define-color dialog_bg_color ${C[base]};
@define-color dialog_fg_color ${C[text]};
@define-color popover_bg_color ${C[surface0]};
@define-color popover_fg_color ${C[text]};
@define-color shade_color ${C[crust]};
@define-color scrollbar_outline_color ${C[crust]};
@define-color sidebar_bg_color ${C[mantle]};
@define-color sidebar_fg_color ${C[text]};
@define-color sidebar_backdrop_color ${C[base]};
@define-color sidebar_shade_color ${C[crust]};
@define-color thumbnail_bg_color ${C[surface0]};
@define-color thumbnail_fg_color ${C[text]};
EOF
)
  echo "$gtk_css" > "$HOME/.config/gtk-3.0/gtk.css"
  echo "$gtk_css" > "$HOME/.config/gtk-4.0/gtk.css"

  # dconf live reload
  if command -v dconf &>/dev/null; then
    dconf write /org/gnome/desktop/interface/gtk-theme      "'$gtk_base_theme'" 2>/dev/null || true
    dconf write /org/gnome/desktop/interface/color-scheme   "'$scheme'"    2>/dev/null || true
    dconf write /org/gnome/desktop/interface/font-name      "'JetBrainsMono Nerd Font 10'" 2>/dev/null || true
    dconf write /org/gnome/desktop/interface/icon-theme     "'$icons'"     2>/dev/null || true
  fi
}

# ── Btop ────────────────────────────────────────────────────────────────────
gen_btop_theme() {
  local theme_file="$HOME/.config/btop/themes/current.theme"
  mkdir -p "$(dirname "$theme_file")"
  cat > "$theme_file" << EOF
# ${C[name]} — auto-generated by switch-theme.sh
theme[main_bg]="${C[base]}"
theme[main_fg]="${C[text]}"
theme[title]="${C[text]}"
theme[hi_fg]="${C[accent]}"
theme[selected_bg]="${C[surface1]}"
theme[selected_fg]="${C[accent]}"
theme[inactive_fg]="${C[overlay1]}"
theme[graph_text]="${C[accent]}"
theme[meter_bg]="${C[surface1]}"
theme[proc_misc]="${C[rosewater]}"
theme[cpu_box]="${C[accent]}"
theme[mem_box]="${C[accent]}"
theme[net_box]="${C[accent]}"
theme[proc_box]="${C[accent]}"
theme[div_line]="${C[overlay0]}"
theme[temp_start]="${C[green]}"
theme[temp_mid]="${C[yellow]}"
theme[temp_end]="${C[red]}"
theme[cpu_start]="${C[teal]}"
theme[cpu_mid]="${C[sapphire]}"
theme[cpu_end]="${C[accent]}"
theme[free_start]="${C[mauve]}"
theme[free_mid]="${C[lavender]}"
theme[free_end]="${C[blue]}"
theme[cached_start]="${C[sapphire]}"
theme[cached_mid]="${C[blue]}"
theme[cached_end]="${C[accent]}"
theme[available_start]="${C[peach]}"
theme[available_mid]="${C[maroon]}"
theme[available_end]="${C[red]}"
theme[used_start]="${C[green]}"
theme[used_mid]="${C[teal]}"
theme[used_end]="${C[sky]}"
theme[download_start]="${C[peach]}"
theme[download_mid]="${C[maroon]}"
theme[download_end]="${C[red]}"
theme[upload_start]="${C[green]}"
theme[upload_mid]="${C[teal]}"
theme[upload_end]="${C[sky]}"
theme[process_start]="${C[accent]}"
theme[process_mid]="${C[sky]}"
theme[process_end]="${C[mauve]}"
EOF

  local conf="$HOME/.config/btop/btop.conf"
  if [ ! -f "$conf" ]; then
    echo "color_theme = \"$theme_file\"" > "$conf"
  elif grep -q "^color_theme" "$conf"; then
    sed -i "s|^color_theme = .*|color_theme = \"$theme_file\"|" "$conf"
  else
    echo "color_theme = \"$theme_file\"" >> "$conf"
  fi
}

# ── Wallpaper ────────────────────────────────────────────────────────────────
switch_wallpaper() {
  local wp_dir="$HOME/Pictures/Wallpapers/${C[wallpaper_dir]}"
  [ -d "$wp_dir" ] || return
  local wp
  wp=$(find "$wp_dir" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | shuf -n 1)
  [ -n "$wp" ] && awww img "$wp" --transition-type wave --transition-duration 2 2>/dev/null || true
}

# ── Swaync ──────────────────────────────────────────────────────────────────
gen_swaync_style() {
  mkdir -p "$HOME/.config/swaync"
  cat > "$HOME/.config/swaync/style.css" << EOF
/* ${C[name]} — auto-generated by switch-theme.sh */
* {
  all: unset;
  font-size: 14px;
  font-family: "JetBrainsMono Nerd Font";
  transition: 200ms;
}

trough highlight { background: ${C[text]}; }

scale { margin: 0 7px; }

scale trough {
  margin: 0rem 1rem;
  min-height: 8px;
  min-width: 70px;
  border-radius: 12.6px;
}

trough slider {
  margin: -10px;
  border-radius: 12.6px;
  box-shadow: 0 0 2px rgba(0,0,0,0.8);
  transition: all 0.2s ease;
  background-color: ${C[blue]};
}

trough slider:hover {
  box-shadow: 0 0 2px rgba(0,0,0,0.8), 0 0 8px ${C[blue]};
}

trough { background-color: ${C[surface0]}; }

.notification-background {
  box-shadow: 0 0 8px 0 rgba(0,0,0,0.8), inset 0 0 0 1px ${C[surface1]};
  border-radius: 12.6px;
  margin: 18px;
  background: ${C[mantle]};
  color: ${C[text]};
  padding: 0;
}

.notification-background .notification {
  padding: 7px;
  border-radius: 12.6px;
}

.notification-background .notification.critical {
  box-shadow: inset 0 0 7px 0 ${C[red]};
}

.notification .notification-content { margin: 7px; }
.notification .notification-content overlay { margin: 4px; }

.notification-content .summary { color: ${C[text]}; }
.notification-content .time    { color: ${C[subtext0]}; }
.notification-content .body    { color: ${C[subtext1]}; }

.notification > *:last-child > * { min-height: 3.4em; }

.notification-background .close-button {
  margin: 7px;
  padding: 2px;
  border-radius: 6.3px;
  color: ${C[base]};
  background-color: ${C[red]};
}

.notification-background .close-button:hover  { background-color: ${C[maroon]}; }
.notification-background .close-button:active { background-color: ${C[pink]}; }

.notification .notification-action {
  border-radius: 7px;
  color: ${C[text]};
  box-shadow: inset 0 0 0 1px ${C[surface1]};
  margin: 4px;
  padding: 8px;
  background-color: ${C[surface0]};
}

.notification .notification-action:hover  { background-color: ${C[surface1]}; }
.notification .notification-action:active { background-color: ${C[surface2]}; }

.notification.critical progress { background-color: ${C[red]}; }
.notification.low progress,
.notification.normal progress   { background-color: ${C[blue]}; }

.notification progress,
.notification trough,
.notification progressbar {
  border-radius: 12.6px;
  padding: 3px 0;
}

.control-center {
  box-shadow: 0 0 8px 0 rgba(0,0,0,0.8), inset 0 0 0 1px ${C[surface0]};
  border-radius: 12.6px;
  background-color: ${C[base]};
  color: ${C[text]};
  padding: 14px;
}

.control-center .notification-background {
  border-radius: 7px;
  box-shadow: inset 0 0 0 1px ${C[surface1]};
  margin: 4px 10px;
}

.control-center .notification-background .notification {
  border-radius: 7px;
}

.control-center .notification-background .notification.low { opacity: 0.8; }

.control-center .widget-title > label {
  color: ${C[text]};
  font-size: 1.3em;
}

.control-center .widget-title button {
  border-radius: 7px;
  color: ${C[text]};
  background-color: ${C[surface0]};
  box-shadow: inset 0 0 0 1px ${C[surface1]};
  padding: 8px;
}

.control-center .widget-title button:hover  { background-color: ${C[surface1]}; }
.control-center .widget-title button:active { background-color: ${C[surface2]}; }

.control-center .notification-group { margin-top: 10px; }

.control-center .notification-group:focus .notification-background {
  background-color: ${C[surface0]};
}

scrollbar slider { margin: -3px; opacity: 0.8; }
scrollbar trough { margin: 2px 0; }

.widget-dnd {
  margin-top: 5px;
  border-radius: 8px;
  font-size: 1.1rem;
}

.widget-dnd > switch {
  font-size: initial;
  border-radius: 8px;
  background: ${C[surface0]};
  box-shadow: none;
}

.widget-dnd > switch:checked { background: ${C[blue]}; }

.widget-dnd > switch slider {
  background: ${C[surface1]};
  border-radius: 8px;
}

.widget-mpris-player {
  background: ${C[surface0]};
  border-radius: 12.6px;
  color: ${C[text]};
}

.mpris-overlay {
  background-color: ${C[surface0]};
  opacity: 0.9;
  padding: 15px 10px;
}

.widget-mpris-album-art {
  -gtk-icon-size: 100px;
  border-radius: 12.6px;
  margin: 0 10px;
}

.widget-mpris-title    { font-size: 1.2rem; color: ${C[text]}; }
.widget-mpris-subtitle { font-size: 1rem;   color: ${C[subtext1]}; }

.widget-mpris button {
  border-radius: 12.6px;
  color: ${C[text]};
  margin: 0 5px;
  padding: 2px;
}

.widget-mpris button image    { -gtk-icon-size: 1.8rem; }
.widget-mpris button:hover    { background-color: ${C[surface0]}; }
.widget-mpris button:active   { background-color: ${C[surface1]}; }
.widget-mpris button:disabled { opacity: 0.5; }

.widget-volume { padding: 1rem 0; }

.widget-volume label {
  color: ${C[sapphire]};
  padding: 0 1rem;
}

.widget-volume trough highlight   { background: ${C[sapphire]}; }
.widget-backlight trough highlight { background: ${C[yellow]}; }

.widget-backlight label {
  font-size: 1.5rem;
  color: ${C[yellow]};
}

.widget-backlight .KB { padding-bottom: 1rem; }

.image { padding-right: 0.5rem; }
EOF

  swaync-client -rs 2>/dev/null || true
}

# ── Qt (Kvantum + qt5ct/qt6ct) ──────────────────────────────────────────────
switch_qt() {
  local icons="${C[icon_theme]:-Papirus-Dark}"
  local local_kvantum="$HOME/.config/Kvantum"
  local theme_dir="$local_kvantum/quickshell-theme"

  mkdir -p "$theme_dir"

  # Find KvAdaptaDark SVG source
  local svg_src="$local_kvantum/KvAdaptaDark/KvAdaptaDark.svg"
  if [ ! -f "$svg_src" ]; then
    svg_src=$(find /nix/store -maxdepth 5 -name "KvAdaptaDark.svg" \
      -path "*/Kvantum/*" 2>/dev/null | head -1)
  fi

  # Generate SVG with palette colors replacing KvAdaptaDark hardcoded colors
  if [ -n "$svg_src" ] && [ -f "$svg_src" ]; then
    local svg_tmp
    svg_tmp=$(mktemp)
    sed \
      -e "s/#00bcd4/${C[accent]}/gI" \
      -e "s/#00c3dc/${C[accent]}/gI" \
      -e "s/#008dd4/${C[blue]}/gI" \
      -e "s/#4db6ac/${C[teal]}/gI" \
      -e "s/#263238/${C[base]}/g" \
      -e "s/#1e282d/${C[crust]}/g" \
      -e "s/#141b1e/${C[crust]}/g" \
      -e "s/#212b30/${C[crust]}/g" \
      -e "s/#212c31/${C[crust]}/g" \
      -e "s/#222d32/${C[mantle]}/g" \
      -e "s/#29353b/${C[mantle]}/g" \
      -e "s/#2d3a41/${C[mantle]}/g" \
      -e "s/#28343a/${C[surface0]}/g" \
      -e "s/#293439/${C[surface0]}/g" \
      -e "s/#2d393f/${C[surface0]}/g" \
      -e "s/#304048/${C[surface1]}/g" \
      -e "s/#314047/${C[surface1]}/g" \
      -e "s/#39444a/${C[surface1]}/g" \
      -e "s/#3e4a50/${C[surface1]}/g" \
      -e "s/#275f59/${C[surface2]}/g" \
      -e "s/#2d4c4f/${C[surface2]}/g" \
      -e "s/#556165/${C[overlay0]}/g" \
      -e "s/#565b5e/${C[overlay0]}/g" \
      -e "s/#60727c/${C[overlay0]}/g" \
      -e "s/#6c787d/${C[overlay1]}/g" \
      -e "s/#717b81/${C[overlay1]}/g" \
      -e "s/#7f898f/${C[overlay1]}/g" \
      -e "s/#a6afb4/${C[subtext0]}/g" \
      -e "s/#acb1bc/${C[subtext0]}/g" \
      -e "s/#cfd8dc/${C[subtext1]}/g" \
      -e "s/#000931/${C[crust]}/g" \
      -e "s/#192023/${C[crust]}/g" \
      -e "s/#252f35/${C[mantle]}/g" \
      "$svg_src" > "$svg_tmp" && mv -f "$svg_tmp" "$theme_dir/quickshell-theme.svg"
    chmod 644 "$theme_dir/quickshell-theme.svg"
  fi

  # Generate kvconfig: copy KvAdaptaDark (all widget sections) then patch GeneralColors
  local kvcfg_src="$local_kvantum/KvAdaptaDark/KvAdaptaDark.kvconfig"
  if [ ! -f "$kvcfg_src" ]; then
    kvcfg_src=$(find /nix/store -maxdepth 5 -name "KvAdaptaDark.kvconfig" \
      -path "*/Kvantum/*" 2>/dev/null | head -1)
  fi
  if [ -n "$kvcfg_src" ] && [ -f "$kvcfg_src" ]; then
    local kvcfg_tmp
    kvcfg_tmp=$(mktemp)
    sed \
      -e "s|^window\.color=.*|window.color=${C[base]}|" \
      -e "s|^base\.color=.*|base.color=${C[mantle]}|" \
      -e "s|^alt\.base\.color=.*|alt.base.color=${C[crust]}|" \
      -e "s|^button\.color=.*|button.color=${C[surface0]}|" \
      -e "s|^light\.color=.*|light.color=${C[surface1]}|" \
      -e "s|^mid\.light\.color=.*|mid.light.color=${C[surface0]}|" \
      -e "s|^dark\.color=.*|dark.color=${C[crust]}|" \
      -e "s|^mid\.color=.*|mid.color=${C[mantle]}|" \
      -e "s|^highlight\.color=.*|highlight.color=${C[accent]}|" \
      -e "s|^inactive\.highlight\.color=.*|inactive.highlight.color=${C[surface1]}|" \
      -e "s|^text\.color=.*|text.color=${C[text]}|" \
      -e "s|^window\.text\.color=.*|window.text.color=${C[subtext1]}|" \
      -e "s|^button\.text\.color=.*|button.text.color=${C[subtext1]}|" \
      -e "s|^disabled\.text\.color=.*|disabled.text.color=${C[overlay0]}|" \
      -e "s|^tooltip\.text\.color=.*|tooltip.text.color=${C[text]}|" \
      -e "s|^highlight\.text\.color=.*|highlight.text.color=${C[base]}|" \
      -e "s|^link\.color=.*|link.color=${C[blue]}|" \
      -e "s|^link\.visited\.color=.*|link.visited.color=${C[mauve]}|" \
      -e "s|^progress\.indicator\.text\.color=.*|progress.indicator.text.color=${C[base]}|" \
      "$kvcfg_src" > "$kvcfg_tmp" && mv -f "$kvcfg_tmp" "$theme_dir/quickshell-theme.kvconfig"
  fi

  # Activate quickshell-theme
  cat > "$local_kvantum/kvantum.kvconfig" << EOF
[General]
theme=quickshell-theme
EOF

  # qt5ct + qt6ct
  local font_str="JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"
  for ct_dir in "$HOME/.config/qt5ct" "$HOME/.config/qt6ct"; do
    mkdir -p "$ct_dir"
    cat > "$ct_dir/$(basename "$ct_dir").conf" << EOF
[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=$icons
standard_dialogs=default
style=kvantum

[Fonts]
fixed="$font_str"
general="$font_str"
EOF
  done
}

# ── Hyprlock theme ──────────────────────────────────────────────────────────
gen_hyprlock_theme() {
  mkdir -p "$HOME/.config/hypr"
  cat > "$HOME/.config/hypr/hyprlock-theme.conf" << EOF
\$hl_background = ${C[base]#\#}
\$hl_surface    = ${C[surface0]#\#}
\$hl_accent     = ${C[accent]#\#}
\$hl_text       = ${C[text]#\#}
\$hl_red        = ${C[red]#\#}
\$hl_yellow     = ${C[yellow]#\#}
EOF
}

# ── Hyprland borders ────────────────────────────────────────────────────────
live_reload() {
  if command -v hyprctl &>/dev/null; then
    local active_hex="${C[hypr_accent]:-${C[accent]}}"
    active_hex="${active_hex#\#}"
    local inactive_hex="${C[surface0]#\#}"
    hyprctl keyword general:col.active_border "rgba(${active_hex}ff)" 2>/dev/null || true
    hyprctl keyword general:col.inactive_border "rgba(${inactive_hex}ff)" 2>/dev/null || true
  fi
}

# ── Fastfetch ───────────────────────────────────────────────────────────────
gen_fastfetch_config() {
  local cfg="$HOME/.config/fastfetch/config.jsonc"
  [ -f "$cfg" ] || return

  local hex="${C[accent]#\#}"
  local r=$((16#${hex:0:2}))
  local g=$((16#${hex:2:2}))
  local b=$((16#${hex:4:2}))
  local rgb="${r};${g};${b}"

  local dark_accent
  dark_accent=$(printf "#%02x%02x%02x" $((r * 65 / 100)) $((g * 65 / 100)) $((b * 65 / 100)))

  sed -i \
    -e "s/\"1\": \"#[0-9A-Fa-f]\{6\}\"/\"1\": \"${dark_accent}\"/g" \
    -e "s/\"2\": \"#[0-9A-Fa-f]\{6\}\"/\"2\": \"${C[accent]}\"/g" \
    -e "s/\"3\": \"#[0-9A-Fa-f]\{6\}\"/\"3\": \"${dark_accent}\"/g" \
    -e "s/\"4\": \"#[0-9A-Fa-f]\{6\}\"/\"4\": \"${C[accent]}\"/g" \
    -e "s/\"5\": \"#[0-9A-Fa-f]\{6\}\"/\"5\": \"${dark_accent}\"/g" \
    -e "s/\"6\": \"#[0-9A-Fa-f]\{6\}\"/\"6\": \"${C[accent]}\"/g" \
    -e "s/\\\\u001b\\[38;2;[0-9]\\+;[0-9]\\+;[0-9]\\+m/\\\\u001b[38;2;${rgb}m/g" \
    "$cfg"
}

# ── Cider ───────────────────────────────────────────────────────────────────
switch_cider() {
  local theme_dir="$HOME/.config/sh.cider.genten/themes/quickshell"
  mkdir -p "$theme_dir"

  cat > "$theme_dir/theme.yml" << EOF
name: Quickshell Theme
author: quickshell
stylesheets:
  - name: ${C[name]}
    file: quickshell.scss
    description: Auto-generated by switch-theme.sh
version: "1.0"
EOF

  cat > "$theme_dir/quickshell.scss" << EOF
body.body--dark,
body.body--light {
  --accent:   ${C[accent_ui]:-${C[accent]}};
  --text:     ${C[text]};
  --subtext1: ${C[subtext1]};
  --subtext0: ${C[subtext0]};
  --overlay1: ${C[overlay1]};
  --overlay0: ${C[overlay0]};
  --surface0: ${C[surface0]};
  --base:     ${C[base]};
  --mantle:   ${C[mantle]};
  --crust:    ${C[crust]};

  --selection-bg: ${C[accent_ui]:-${C[accent]}}4d;
  --red:   ${C[red]};
  --green: ${C[green]};
  --blue:  ${C[blue]};

  background: var(--crust);
  color: var(--text);
  --textDefault: var(--text);
  --systemPrimary: var(--text);
  --systemSecondary: var(--text);
  --systemTertiary: var(--surface0);
  --systemQuinary: var(--selection-bg);
  --systemQuaternary: var(--selection-bg);
  --keyColor: var(--accent);
  --musicKeyColor: var(--accent);
  --tracklistAltRowColor: transparent;
  --vibrantDivider: var(--surface0);
  --q-primary: var(--accent);
  --q-info: var(--blue);
}
EOF
}

# ── Vesktop ─────────────────────────────────────────────────────────────────
switch_vesktop() {
  local theme_file="$HOME/.config/vesktop/themes/quickshell-theme.css"
  mkdir -p "$(dirname "$theme_file")"
  cat > "$theme_file" << EOF
/**
 * @name quickshell-theme
 * @description ${C[name]} — auto-generated by switch-theme.sh
 * @author quickshell
 * @version 1.0.0
 */

:root,
.theme-dark,
.theme-light {
  /* === Backgrounds (new Discord variable names) === */
  --app-frame-background:           ${C[crust]};
  --background-base-lowest:         ${C[crust]};
  --background-base-lower:          ${C[mantle]};
  --background-base-low:            ${C[mantle]};
  --background-surface-high:        ${C[base]};
  --background-surface-higher:      ${C[surface0]};
  --background-accent:              ${C[surface1]};
  --chat-background:                ${C[base]};
  --home-background:                ${C[base]};
  --modal-background:               ${C[base]};
  --channeltextarea-background:      ${C[mantle]};
  --input-background-default:        ${C[crust]};
  --input-text-default:              ${C[text]};
  --input-placeholder-text-default:  ${C[subtext1]};
  --input-border-default:            ${C[overlay0]};
  --custom-status-bubble-background: ${C[crust]};
  --border-normal:                   ${C[surface0]};
  --border-faint:                    ${C[surface0]}60;
  --channel-icon:                    ${C[overlay1]};
  --interactive-background-selected: ${C[surface0]}60;
  --interactive-background-active:   ${C[surface0]}40;

  /* === Text (new names) === */
  --text-default:                  ${C[text]};
  --text-muted:                    ${C[subtext0]};
  --text-subtle:                   ${C[subtext1]};
  --text-link:                     ${C[blue]};
  --text-positive:                 ${C[green]};
  --text-warning:                  ${C[yellow]};
  --text-danger:                   ${C[red]};
  --text-brand:                    ${C[accent]};

  /* === Interactive === */
  --interactive-text-default:      ${C[text]};
  --interactive-background-hover:  ${C[surface0]}60;
  --channels-default:              ${C[overlay1]};
  --icon-muted:                    ${C[overlay1]};

  /* === Brand / Accent === */
  --brand-500:                     ${C[accent]};
  --brand-560:                     ${C[accent]};
  --brand-600:                     ${C[accent]};
  --brand-700:                     ${C[mauve]};
  --control-primary-background-default: ${C[accent]};
  --control-secondary-background-default: ${C[surface1]};
  --logo-primary:                  ${C[accent]};

  /* === Scrollbar === */
  --scrollbar-thin-thumb:          ${C[surface1]};
  --scrollbar-auto-thumb:          ${C[surface1]};
  --scrollbar-auto-track:          ${C[mantle]};

  /* === Brand spectrum (covers selected home button) === */
  --brand-100: ${C[surface0]};
  --brand-200: ${C[surface0]};
  --brand-300: ${C[surface1]};
  --brand-360: ${C[surface2]};
  --brand-400: ${C[overlay0]};
  --brand-430: ${C[overlay0]};
  --brand-460: ${C[overlay1]};
  --brand-500: ${C[accent]};
  --brand-530: ${C[accent]};
  --brand-560: ${C[accent]};
  --brand-600: ${C[accent]};
  --brand-630: ${C[mauve]};
  --brand-660: ${C[mauve]};
  --brand-700: ${C[mauve]};
  --brand-800: ${C[mauve]};
  --brand-900: ${C[base]};

  /* === Missing backgrounds === */
  --background-surface-highest:    ${C[surface1]} !important;
  --bg-surface-raised:             ${C[mantle]};
  --background-gradient-highest:   ${C[mantle]};
  --chat-background-default:       ${C[base]};
  --chat-border:                   ${C[crust]};
  --__header-bar-background:       ${C[mantle]} !important;
  --custom-channel-members-bg:     ${C[mantle]};
  --card-background-default:       ${C[surface0]} !important;
  --modal-footer-background:       ${C[base]};
  --user-profile-overlay-background: ${C[mantle]};
  --background-secondary-alt:      ${C[mantle]} !important;
  --background-mod-subtle:         ${C[surface0]}40 !important;
  --background-mod-strong:         ${C[surface1]}72 !important;

  /* === Legacy variables (older Discord/Vencord) === */
  --background-primary:            ${C[base]};
  --background-secondary:          ${C[mantle]};
  --background-tertiary:           ${C[crust]};
  --background-floating:           ${C[mantle]};
  --background-modifier-hover:     ${C[surface0]}60;
  --background-modifier-active:    ${C[surface1]}80;
  --background-modifier-selected:  ${C[surface1]}60;
  --text-normal:                   ${C[text]};
  --header-primary:                ${C[text]};
  --header-secondary:              ${C[subtext1]};
  --interactive-normal:            ${C[subtext1]};
  --interactive-hover:             ${C[text]};
  --interactive-active:            ${C[accent]};
  --interactive-muted:             ${C[overlay1]};
  --focus-primary:                 ${C[accent]};
  --brand-experiment:              ${C[accent]};
  --brand-experiment-560:          ${C[accent]};
}

/* Fix Discord home button selected state (SVG circle) */
.visual-refresh.theme-dark svg[class^=selectedIcon_]>circle[fill=white],
.visual-refresh .theme-dark svg[class^=selectedIcon_]>circle[fill=white],
svg[class^=selectedIcon_]>circle[fill=white] {
  fill: ${C[crust]};
}
EOF
}

# ── Steam (Millennium Quick CSS) ─────────────────────────────────────────────
switch_steam() {
  local quickcss="$HOME/.config/millennium/quickcss.css"
  [ -f "$quickcss" ] || return

  cat > "$quickcss" << EOF
/* Quickshell theme — auto-generated by switch-theme.sh */
:root {
    --color-light:   ${C[surface1]} !important;
    --color-dark:    ${C[mantle]}   !important;
    --color-darker:  ${C[base]}     !important;
    --color-darkest: ${C[crust]}    !important;
    --scrollbar:     ${C[surface1]} !important;
    --black:         ${C[crust]}    !important;
    --black-ish:     ${C[crust]}    !important;
    --realblack:     ${C[crust]}    !important;
    --blacker-ish:   ${C[crust]}    !important;
    --blacker:       ${C[crust]}    !important;
    --lightblack:    ${C[crust]}    !important;
    --darkergrey:    ${C[crust]}    !important;
    --bedarkgrey:    ${C[crust]}    !important;
    --thegrey:       ${C[mantle]}   !important;
    --begrey:        ${C[surface0]} !important;
    --littlegrey:    ${C[surface0]} !important;
    --darkgrey:      ${C[base]}     !important;
    --grey:          ${C[surface0]} !important;
    --lightgrey:     ${C[surface1]} !important;
    --lightergrey:   ${C[surface0]} !important;
    --grey-ish:      ${C[surface2]} !important;
    --darkerwhite:   ${C[subtext0]} !important;
    --darkwhite:     ${C[subtext1]} !important;
    --white:         ${C[text]}     !important;
    --ingame:        ${C[green]}    !important;
    --online:        ${C[teal]}     !important;
    --offline:       ${C[overlay0]} !important;
}
EOF
}

# ── OBS Studio ──────────────────────────────────────────────────────────────
switch_obs() {
  local theme_dir="$HOME/.config/obs-studio/themes"
  local theme_file="$theme_dir/Quickshell.obt"
  local user_ini="$HOME/.config/obs-studio/user.ini"
  mkdir -p "$theme_dir"

  local is_dark
  is_dark=$([ "$THEME" = "gruvbox-light" ] && echo "false" || echo "true")

  cat > "$theme_file" << EOF
@OBSThemeMeta {
    name: 'Quickshell';
    id: 'io.github.quickshell';
    extends: 'com.obsproject.Yami';
    author: 'quickshell';
    dark: '$is_dark';
}

@OBSThemeVars {
    --bg_window: ${C[mantle]};
    --bg_base: ${C[base]};
    --bg_preview: ${C[crust]};

    --primary: ${C[accent_ui]:-${C[accent]}};
    --primary_light: ${C[blue]};
    --primary_lighter: ${C[sky]};
    --primary_dark: ${C[accent_ui]:-${C[accent]}};
    --primary_darker: ${C[mauve]};

    --warning: ${C[yellow]};
    --danger: ${C[red]};

    --text: ${C[text]};
    --text_light: ${C[subtext1]};
    --text_muted: ${C[subtext0]};
    --text_disabled: ${C[overlay0]};
    --text_inactive: ${C[text]};

    --input_bg: ${C[surface0]};
    --input_bg_hover: ${C[surface1]};
    --input_bg_focus: ${C[surface0]};
    --input_border: ${C[overlay0]};
    --input_border_hover: ${C[overlay1]};
    --input_border_focus: ${C[accent_ui]:-${C[accent]}};

    --border_color: ${C[surface1]};

    --button_bg: ${C[surface0]};
    --button_bg_hover: ${C[surface1]};
    --button_bg_down: ${C[surface2]};
    --button_bg_disabled: ${C[mantle]};
    --button_border: ${C[surface0]};
    --button_border_hover: ${C[overlay0]};
    --button_border_focus: ${C[overlay0]};

    --scrollbar_handle: ${C[surface1]};
    --scrollbar_bg: ${C[base]};
    --scrollbar_hover: ${C[surface2]};
    --scrollbar_down: ${C[overlay0]};
    --scrollbar_border: ${C[surface1]};

    --tab_bg: ${C[mantle]};
    --tab_bg_hover: ${C[surface0]};
    --tab_bg_down: ${C[accent_ui]:-${C[accent]}};
    --tab_bg_disabled: ${C[mantle]};
    --tab_border: ${C[surface1]};
    --tab_border_hover: ${C[overlay0]};
    --tab_border_focus: ${C[accent_ui]:-${C[accent]}};
    --tab_border_selected: ${C[accent_ui]:-${C[accent]}};
}
EOF

  if [ -f "$user_ini" ]; then
    if grep -q "^Theme=" "$user_ini"; then
      sed -i "s|^Theme=.*|Theme=io.github.quickshell|" "$user_ini"
    else
      sed -i '/^\[Appearance\]/a Theme=io.github.quickshell' "$user_ini"
    fi
  fi
}


# ── LibreWolf ────────────────────────────────────────────────────────────────
switch_librewolf() {
  local profile_dir="$HOME/.librewolf/$(awk -F= '/^Path=/{print $2; exit}' "$HOME/.librewolf/profiles.ini" 2>/dev/null)"
  local chrome_dir="$profile_dir/chrome"
  local user_js="$profile_dir/user.js"
  local user_chrome="$chrome_dir/userChrome.css"
  local user_content="$chrome_dir/userContent.css"

  mkdir -p "$chrome_dir"

  local dark_mode
  case "${C[gtk_scheme]}" in
    prefer-light) dark_mode=0 ;;
    *)            dark_mode=1 ;;
  esac

  {
    echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'
    echo "user_pref(\"ui.systemUsesDarkTheme\", ${dark_mode});"
  } > "$user_js"

  cat > "$user_chrome" << EOF
/* Quickshell theme - auto-generated, do not edit */
:root {
  --toolbox-bgcolor-inactive:     ${C[mantle]} !important;
  --toolbarbutton-icon-fill:      ${C[accent]} !important;
  --lwt-text-color:               ${C[text]} !important;
  --toolbar-field-color:          ${C[text]} !important;
  --tab-selected-textcolor:       ${C[text]} !important;
  --toolbar-field-focus-color:    ${C[text]} !important;
  --toolbar-color:                ${C[text]} !important;
  --newtab-text-primary-color:    ${C[text]} !important;
  --arrowpanel-color:             ${C[text]} !important;
  --arrowpanel-background:        ${C[base]} !important;
  --sidebar-text-color:           ${C[text]} !important;
  --lwt-sidebar-text-color:       ${C[text]} !important;
  --lwt-sidebar-background-color: ${C[crust]} !important;
  --toolbar-bgcolor:              ${C[surface0]} !important;
  --newtab-background-color:      ${C[base]} !important;
}

#permissions-granted-icon {
  color: ${C[mantle]} !important;
}

.sidebar-placesTree {
  background-color: ${C[base]} !important;
}

#TabsToolbar {
  background-color: ${C[mantle]} !important;
  color: ${C[text]} !important;
}

#TabsToolbar * {
  color: ${C[text]} !important;
}

hbox#titlebar {
  background-color: ${C[mantle]} !important;
  color: ${C[text]} !important;
}

.urlbar-background {
  background-color: ${C[base]} !important;
}

.urlbarView-url {
  color: ${C[accent]} !important;
}

#navigator-toolbox,
#nav-bar,
#toolbar-menubar,
#PersonalToolbar {
  background-color: ${C[mantle]} !important;
  color: ${C[text]} !important;
  border-color: ${C[surface1]} !important;
}
EOF

  cat > "$user_content" << EOF
/* Quickshell theme - auto-generated, do not edit */
@-moz-document url-prefix("about:") {
  :root {
    --in-content-page-color:      ${C[text]} !important;
    --color-accent-primary:       ${C[accent]} !important;
    --color-accent-primary-hover: ${C[blue]} !important;
    background-color:             ${C[base]} !important;
    --in-content-page-background: ${C[base]} !important;
  }
}

@-moz-document url("about:newtab"), url("about:home") {
  :root {
    --newtab-background-color:           ${C[base]} !important;
    --newtab-background-color-secondary: ${C[surface0]} !important;
    --newtab-element-hover-color:        ${C[surface0]} !important;
    --newtab-text-primary-color:         ${C[text]} !important;
    --newtab-wordmark-color:             ${C[text]} !important;
    --newtab-primary-action-background:  ${C[accent]} !important;
  }
}

@-moz-document url-prefix("about:preferences") {
  :root {
    --in-content-text-color:     ${C[text]} !important;
    --link-color:                ${C[accent]} !important;
    --link-color-hover:          ${C[blue]} !important;
    --in-content-box-background: ${C[surface0]} !important;
  }

  .main-content {
    background-color: ${C[crust]} !important;
  }
}
EOF
}

# ── Userstyles (Stylus via userContent.css + Helium file-watch) ─────────────
gen_userstyles() {
  local cache_dir="$HOME/.config/quickshell/scripts/userstyles-cache"
  local compile_js="$HOME/.config/quickshell/scripts/compile-userstyle.js"
  local user_content="$HOME/.librewolf/$(awk -F= '/^Path=/{print $2; exit}' "$HOME/.librewolf/profiles.ini" 2>/dev/null)/chrome/userContent.css"
  local helium_css="$HOME/.config/quickshell/scripts/helium-userstyles.user.css"

  local palette
  palette=$(printf '{
    "rosewater":"%s","flamingo":"%s","pink":"%s","mauve":"%s",
    "red":"%s","maroon":"%s","peach":"%s","yellow":"%s",
    "green":"%s","teal":"%s","sky":"%s","sapphire":"%s",
    "blue":"%s","lavender":"%s","text":"%s","subtext1":"%s",
    "subtext0":"%s","overlay2":"%s","overlay1":"%s","overlay0":"%s",
    "surface2":"%s","surface1":"%s","surface0":"%s",
    "base":"%s","mantle":"%s","crust":"%s","accentColor":"%s"
  }' \
    "${C[rosewater]}" "${C[flamingo]}" "${C[pink]}"     "${C[mauve]}"   \
    "${C[red]}"       "${C[maroon]}"   "${C[peach]}"    "${C[yellow]}"  \
    "${C[green]}"     "${C[teal]}"     "${C[sky]}"      "${C[sapphire]}"\
    "${C[blue]}"      "${C[lavender]}" "${C[text]}"     "${C[subtext1]}"\
    "${C[subtext0]}"  "${C[overlay2]}" "${C[overlay1]}" "${C[overlay0]}"\
    "${C[surface2]}"  "${C[surface1]}" "${C[surface0]}"                 \
    "${C[base]}"      "${C[mantle]}"   "${C[crust]}"    "${C[cat_accent]}")

  # Start with the about: rules already in userContent.css (everything before userstyles block)
  # then append compiled site CSS
  local tmp helium_tmp
  tmp=$(mktemp)
  helium_tmp=$(mktemp)
  trap 'rm -f "$tmp" "$helium_tmp"' EXIT

  # Keep the existing about: page rules
  sed '/^\/\* --- userstyles ---/,$d' "$user_content" > "$tmp" 2>/dev/null || cp "$user_content" "$tmp"
  echo "/* --- userstyles --- */" >> "$tmp"

  # Helium header — UserCSS format so Stylus can install/auto-update it
  local version
  version=$(date +%Y%m%d%H%M%S)
  cat > "$helium_tmp" << EOF
/* ==UserStyle==
@name         Quickshell Theme
@namespace    quickshell.helium
@version      ${version}
@description  Auto-generated by switch-theme.sh — do not edit
==/UserStyle== */
EOF

  local sites=(youtube twitch twitter instagram reddit github codeberg tuta claude anilist duckduckgo wikipedia)
  for site in "${sites[@]}"; do
    local less_file="$cache_dir/$site.user.less"
    [ -f "$less_file" ] || continue
    local compiled
    compiled=$(qs-compile-userstyle "$less_file" "$palette" 2>/dev/null) || continue
    echo "/* == $site == */" | tee -a "$tmp" >> "$helium_tmp"
    printf '%s\n' "$compiled" | tee -a "$tmp" >> "$helium_tmp"
  done

  mv "$tmp" "$user_content"
  mv "$helium_tmp" "$helium_css"
}

# ── Jellyfin ────────────────────────────────────────────────────────────────
switch_jellyfin() {
  local conf="$HOME/.config/jellyfin-theme.conf"
  [ -f "$conf" ] || return 0
  source "$conf"
  [ -n "$JELLYFIN_URL" ] && [ -n "$JELLYFIN_API_KEY" ] || return 0

  local css
  case "$THEME" in
    pastelglow)
      css=":root {
    --main-color: ${C[accent]};
    --main-background: ${C[base]};
    --main-background-transparent: ${C[base]}dd;
    --dark-background: ${C[crust]};
    --second-background: ${C[mantle]};
    --hover-background: ${C[surface0]};
    --main-text: ${C[text]};
    --white-text: ${C[text]};
    --dimmer-text: ${C[overlay1]};
    --red-color: ${C[red]};
    --green-color: ${C[green]};
    --yellow-color: ${C[yellow]};
}" ;;
    gruvbox-light)
      css="@import url('https://jellyfin.catppuccin.com/theme.css');
@import url('https://jellyfin.catppuccin.com/catppuccin-latte.css');
:root { --main-color: var(--yellow); }" ;;
    *)
      css="@import url('https://jellyfin.catppuccin.com/theme.css');
:root {
    --main-color: ${C[accent]};
    --main-background: ${C[base]};
    --main-background-transparent: ${C[base]}dd;
    --dark-background: ${C[crust]};
    --second-background: ${C[mantle]};
    --hover-background: ${C[surface0]};
    --main-text: ${C[text]};
    --white-text: ${C[text]};
    --dimmer-text: ${C[overlay1]};
    --red-color: ${C[red]};
    --green-color: ${C[green]};
    --yellow-color: ${C[yellow]};
}" ;;
  esac

  local css_escaped
  css_escaped=$(printf '%s' "$css" | sed 's/\\/\\\\/g; s/"/\\"/g; s/$/\\n/' | tr -d '\n' | sed 's/\\n$//')
  local payload="{\"CustomCss\":\"${css_escaped}\",\"LoginDisclaimer\":null,\"SplashscreenEnabled\":false}"

  curl -sf -X POST \
    -H "X-Emby-Token: $JELLYFIN_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$payload" \
    "$JELLYFIN_URL/System/Configuration/Branding" > /dev/null
}

# ── Obsidian ────────────────────────────────────────────────────────────────
switch_obsidian() {
  local vault_obsidian="/home/honey/Obsidian Vault/.obsidian"
  local appearance="$vault_obsidian/appearance.json"
  [ -f "$appearance" ] || return 0

  local obsidian_theme
  [ "$THEME" = "gruvbox-light" ] && obsidian_theme="moonstone" || obsidian_theme="obsidian"

  mkdir -p "$vault_obsidian/snippets"
  cat > "$vault_obsidian/snippets/quickshell-theme.css" << EOF
/* auto-generated by switch-theme.sh */
.theme-dark, .theme-light {
  --background-primary:           ${C[base]};
  --background-primary-alt:       ${C[mantle]};
  --background-secondary:         ${C[mantle]};
  --background-secondary-alt:     ${C[crust]};
  --background-modifier-border:   ${C[surface0]};
  --background-modifier-hover:    ${C[surface0]};
  --background-modifier-active-hover: ${C[surface1]};
  --background-modifier-form-field: ${C[surface0]};

  --text-normal:                  ${C[text]};
  --text-muted:                   ${C[subtext0]};
  --text-faint:                   ${C[overlay0]};
  --text-on-accent:               ${C[base]};
  --text-highlight-bg:            ${C[surface1]};

  --interactive-normal:           ${C[surface0]};
  --interactive-hover:            ${C[surface1]};
  --interactive-accent:           ${C[accent]};
  --interactive-accent-hover:     ${C[accent]};
  --color-accent:                 ${C[accent]};
  --color-accent-1:               ${C[accent]};
  --color-accent-2:               ${C[overlay1]};

  --link-color:                   ${C[blue]};
  --link-external-color:          ${C[sapphire]};
  --link-unresolved-color:        ${C[overlay1]};

  --tag-background:               ${C[surface1]};
  --tag-color:                    ${C[accent]};
  --tag-border-color:             ${C[surface2]};

  --code-background:              ${C[mantle]};
  --code-normal:                  ${C[green]};
  --code-comment:                 ${C[overlay0]};
  --code-string:                  ${C[yellow]};
  --code-keyword:                 ${C[mauve]};
  --code-function:                ${C[blue]};
  --code-operator:                ${C[teal]};
  --code-property:                ${C[red]};

  --table-header-background:      ${C[surface0]};
  --table-row-even-background:    ${C[mantle]};
  --table-row-odd-background:     ${C[base]};

  --titlebar-background:          ${C[crust]};
  --titlebar-background-focused:  ${C[mantle]};
  --titlebar-text-color:          ${C[text]};

  --modal-background:             ${C[mantle]};
  --prompt-background:            ${C[mantle]};
  --prompt-border-color:          ${C[surface1]};

  --scrollbar-bg:                 transparent;
  --scrollbar-thumb-bg:           ${C[surface1]};
  --scrollbar-active-thumb-bg:    ${C[surface2]};

  --color-red:                    ${C[red]};
  --color-orange:                 ${C[peach]};
  --color-yellow:                 ${C[yellow]};
  --color-green:                  ${C[green]};
  --color-cyan:                   ${C[teal]};
  --color-blue:                   ${C[blue]};
  --color-purple:                 ${C[mauve]};
  --color-pink:                   ${C[pink]};
}
EOF

  cat > "$appearance" << EOF
{
  "cssTheme": "",
  "accentColor": "${C[accent]}",
  "theme": "$obsidian_theme",
  "enabledCssSnippets": ["quickshell-theme"]
}
EOF
}

# ── aerc ────────────────────────────────────────────────────────────────────
switch_aerc() {
  local aerc_conf="$HOME/.config/aerc/aerc.conf"
  [ -f "$aerc_conf" ] || return 0

  mkdir -p "$HOME/.config/aerc/stylesets"
  cat > "$HOME/.config/aerc/stylesets/quickshell-theme" << EOF
*.default=true
*.normal=true

default.fg=${C[text]}

error.fg=${C[red]}
warning.fg=${C[peach]}
success.fg=${C[green]}

tab.fg=${C[overlay0]}
tab.bg=${C[mantle]}
tab.selected.fg=${C[text]}
tab.selected.bg=${C[base]}
tab.selected.bold=true

border.fg=${C[crust]}
border.bold=true

msglist_unread.bold=true
msglist_flagged.fg=${C[yellow]}
msglist_flagged.bold=true
msglist_result.fg=${C[blue]}
msglist_result.bold=true
msglist_*.selected.bold=true
msglist_*.selected.bg=${C[surface0]}

dirlist_*.selected.bold=true
dirlist_*.selected.bg=${C[surface0]}

statusline_default.fg=${C[subtext1]}
statusline_default.bg=${C[surface0]}
statusline_error.bold=true
statusline_success.bold=true

selector_focused.bg=${C[surface0]}

completion_default.selected.bg=${C[surface0]}

[viewer]
url.fg=${C[blue]}
url.underline=true
header.bold=true
signature.dim=true
diff_meta.bold=true
diff_chunk.fg=${C[blue]}
diff_chunk_func.fg=${C[blue]}
diff_chunk_func.bold=true
diff_add.fg=${C[green]}
diff_del.fg=${C[red]}
quote_*.fg=${C[overlay0]}
quote_1.fg=${C[subtext1]}
EOF

  sed -i 's|^#\?styleset-name=.*|styleset-name=quickshell-theme|' "$aerc_conf"
}

# ── gdu ─────────────────────────────────────────────────────────────────────
switch_gdu() {
  local config="$HOME/.gdu.yaml"
  [ -f "$config" ] || return 0

  local style_tmp tmp
  style_tmp=$(mktemp)
  tmp=$(mktemp)

  cat > "$style_tmp" << EOF
style:
    footer:
        text-color: '${C[text]}'
        background-color: '${C[surface0]}'
        number-color: '${C[peach]}'
    selected-row:
        text-color: '${C[base]}'
        background-color: '${C[accent]}'
    result-row:
        number-color: '${C[peach]}'
        directory-color: '${C[blue]}'
    header:
        text-color: '${C[text]}'
        background-color: '${C[surface0]}'
        hidden: false
    progress-modal:
        current-item-path-max-len: 0
    use-old-size-bar: false
EOF

  awk '
    /^style:/ { in_style=1; while ((getline line < style_file) > 0) print line; close(style_file); next }
    in_style && /^[a-zA-Z]/ { in_style=0 }
    !in_style { print }
  ' style_file="$style_tmp" "$config" > "$tmp" && mv "$tmp" "$config"

  rm -f "$style_tmp"
}

# ── Blender ──────────────────────────────────────────────────────────────────
switch_blender() {
  local blender_dir="$HOME/.config/blender/5.0"
  local preset_dir="$blender_dir/scripts/presets/interface_theme"
  local preset="$preset_dir/Quickshell.py"
  local apply_script="$blender_dir/scripts/apply-quickshell-theme.py"

  mkdir -p "$preset_dir"

  # hex (#rrggbb) → "r, g, b, a" floats
  h4() { local h="${1#\#}"; awk "BEGIN{printf \"%.6f, %.6f, %.6f, ${2:-1.0}\", 0x${h:0:2}/255, 0x${h:2:2}/255, 0x${h:4:2}/255}"; }
  # hex → "r, g, b" floats (no alpha, for wcol.text)
  h3() { local h="${1#\#}"; awk "BEGIN{printf \"%.6f, %.6f, %.6f\", 0x${h:0:2}/255, 0x${h:2:2}/255, 0x${h:4:2}/255}"; }

  local base;     base=$(h4 "${C[base]}")
  local mantle;   mantle=$(h4 "${C[mantle]}")
  local crust;    crust=$(h4 "${C[crust]}")
  local surf0;    surf0=$(h4 "${C[surface0]}")
  local surf1;    surf1=$(h4 "${C[surface1]}")
  local text4;    text4=$(h4 "${C[text]}")
  local text3;    text3=$(h3 "${C[text]}")
  local sub3;     sub3=$(h3 "${C[subtext0]}")
  local ov3;      ov3=$(h3 "${C[overlay0]}")
  local _accent="${C[accent_ui]:-${C[accent]}}"
  local accent4;  accent4=$(h4 "$_accent")
  local accent3;  accent3=$(h3 "$_accent")
  local red4;     red4=$(h4 "${C[red]}")
  local green4;   green4=$(h4 "${C[green]}")
  local yellow4;  yellow4=$(h4 "${C[yellow]}")

  cat > "$preset" << EOF
import bpy

t  = bpy.context.preferences.themes[0]
ui = t.user_interface

def wcol(w, inner, inner_sel, item, text, text_sel, outline=None):
    w.inner     = inner
    w.inner_sel = inner_sel
    w.item      = item
    w.text      = text
    w.text_sel  = text_sel
    if outline is not None:
        w.outline = outline

base    = ($base)
mantle  = ($mantle)
crust   = ($crust)
surf0   = ($surf0)
surf1   = ($surf1)
text4   = ($text4)
text3   = ($text3)
sub3    = ($sub3)
ov3     = ($ov3)
accent4 = ($accent4)
accent3 = ($accent3)
red4    = ($red4)
green4  = ($green4)
yellow4 = ($yellow4)

# Standard widgets
for w in [ui.wcol_regular, ui.wcol_tool, ui.wcol_toolbar_item,
          ui.wcol_radio, ui.wcol_option, ui.wcol_toggle,
          ui.wcol_num, ui.wcol_numslider, ui.wcol_progress, ui.wcol_curve]:
    wcol(w, surf0, accent4, accent4, text3, text3[:3], mantle)

# Text input
wcol(ui.wcol_text, mantle, mantle, accent4, text3, text3, surf0)

# Box / panel background
wcol(ui.wcol_box, base, surf0, accent4, text3, text3, surf0)

# Tabs
wcol(ui.wcol_tab, mantle, surf1, accent4, sub3, text3, mantle)

# Menus
wcol(ui.wcol_menu,      surf0,  accent4, accent4, text3, text3, surf1)
wcol(ui.wcol_pulldown,  surf0,  accent4, accent4, text3, text3, surf1)
wcol(ui.wcol_menu_back, mantle, surf0,   accent4, text3, text3, surf0)
wcol(ui.wcol_menu_item, (0,0,0,0), accent4, accent4, text3, text3)
wcol(ui.wcol_pie_menu,  mantle, accent4, accent4, text3, text3, surf0)

# Tooltip
wcol(ui.wcol_tooltip, surf0, surf1, accent4, text3, text3, surf1)

# Scrollbar
wcol(ui.wcol_scroll,    base,   surf1, surf1, text3, text3, mantle)

# List items
wcol(ui.wcol_list_item, (0,0,0,0), surf0, accent4, text3, text3)

# 3-tuple versions for RGB-only properties
base3   = base[:3]
mantle3 = mantle[:3]
surf0_3 = surf0[:3]
surf1_3 = surf1[:3]

# Panel backgrounds (back/header = RGBA, text/title = RGB)
ui.panel_back     = base
ui.panel_sub_back = mantle
ui.panel_header   = mantle
ui.panel_text     = text3
ui.panel_title    = text3

# Editor borders
ui.editor_border         = surf0_3   # RGB
ui.editor_outline        = surf1     # RGBA
ui.editor_outline_active = accent4   # RGBA

# Apply header/text to all editor spaces
for area in ['view_3d', 'node_editor', 'properties', 'outliner',
             'file_browser', 'sequence_editor', 'text_editor',
             'nla_editor', 'dopesheet', 'graph_editor',
             'image_editor', 'console', 'info', 'preferences']:
    try:
        space = getattr(t, area).space
        space.header         = mantle  # RGBA
        space.header_text    = text3   # RGB
        space.header_text_hi = accent3 # RGB
        space.text           = text3   # RGB
        space.text_hi        = accent3 # RGB
        space.title          = text3   # RGB
    except Exception:
        pass

# 3D viewport background
t.view_3d.space.gradients.background_type = 'SINGLE_COLOR'
t.view_3d.space.gradients.gradient        = base3
t.view_3d.space.gradients.high_gradient   = base3

# 3D viewport overlay
t.view_3d.grid            = surf0     # RGBA
t.view_3d.object_selected = accent3   # RGB
t.view_3d.object_active   = accent3   # RGB
t.view_3d.wire            = surf1_3   # RGB

# Background for all other editor spaces
for area in ['node_editor', 'outliner', 'sequence_editor', 'graph_editor',
             'nla_editor', 'dopesheet', 'file_browser', 'text_editor',
             'image_editor', 'console', 'info', 'preferences', 'properties']:
    try:
        sp = getattr(t, area).space
        if hasattr(sp, 'back'):
            sp.back = base3
    except Exception:
        pass

# Properties panel highlight color (active object match)
try:
    t.properties.match = accent3
except Exception:
    pass
EOF

  # Apply script: load preset + save prefs (run only if Blender is not open)
  cat > "$apply_script" << EOF
import bpy, os
exec(open(os.path.expanduser('$preset')).read())
bpy.ops.wm.save_userpref()
print("Quickshell theme applied.")
EOF

  if ! pgrep -x blender > /dev/null; then
    blender --background --python "$apply_script" &>/dev/null &
  fi
}

# ── KDE globals (kdeglobals) ─────────────────────────────────────────────────
gen_kdeglobals() {
  # Convert hex color (#rrggbb) to KDE decimal format (r,g,b)
  h2r() { printf "%d,%d,%d" "0x${1:1:2}" "0x${1:3:2}" "0x${1:5:2}"; }

  local win;     win=$(h2r "${C[base]}")
  local win_alt; win_alt=$(h2r "${C[mantle]}")
  local crust;   crust=$(h2r "${C[crust]}")
  local surf0;   surf0=$(h2r "${C[surface0]}")
  local surf1;   surf1=$(h2r "${C[surface1]}")
  local text;    text=$(h2r "${C[text]}")
  local sub0;    sub0=$(h2r "${C[subtext0]}")
  local ov0;     ov0=$(h2r "${C[overlay0]}")
  local accent;  accent=$(h2r "${C[accent]}")
  local blue;    blue=$(h2r "${C[blue]}")
  local mauve;   mauve=$(h2r "${C[mauve]}")
  local red;     red=$(h2r "${C[red]}")
  local yellow;  yellow=$(h2r "${C[yellow]}")
  local green;   green=$(h2r "${C[green]}")

  cat > "$HOME/.config/kdeglobals" << EOF
[Colors:Button]
BackgroundAlternate=$surf1
BackgroundNormal=$surf0
DecorationFocus=$accent
DecorationHover=$surf1
ForegroundActive=$accent
ForegroundInactive=$ov0
ForegroundLink=$blue
ForegroundNegative=$red
ForegroundNeutral=$yellow
ForegroundNormal=$text
ForegroundPositive=$green
ForegroundVisited=$mauve

[Colors:Complementary]
BackgroundAlternate=$crust
BackgroundNormal=$crust
DecorationFocus=$accent
DecorationHover=$surf0
ForegroundActive=$accent
ForegroundInactive=$ov0
ForegroundLink=$blue
ForegroundNegative=$red
ForegroundNeutral=$yellow
ForegroundNormal=$text
ForegroundPositive=$green
ForegroundVisited=$mauve

[Colors:Header]
BackgroundAlternate=$win_alt
BackgroundNormal=$win_alt
DecorationFocus=$accent
DecorationHover=$surf0
ForegroundActive=$accent
ForegroundInactive=$ov0
ForegroundLink=$blue
ForegroundNegative=$red
ForegroundNeutral=$yellow
ForegroundNormal=$text
ForegroundPositive=$green
ForegroundVisited=$mauve

[Colors:Selection]
BackgroundAlternate=$surf1
BackgroundNormal=$accent
DecorationFocus=$accent
DecorationHover=$surf1
ForegroundActive=$win
ForegroundInactive=$win_alt
ForegroundLink=$blue
ForegroundNegative=$red
ForegroundNeutral=$yellow
ForegroundNormal=$win
ForegroundPositive=$green
ForegroundVisited=$mauve

[Colors:Tooltip]
BackgroundAlternate=$surf0
BackgroundNormal=$surf0
DecorationFocus=$accent
DecorationHover=$surf1
ForegroundActive=$accent
ForegroundInactive=$ov0
ForegroundLink=$blue
ForegroundNegative=$red
ForegroundNeutral=$yellow
ForegroundNormal=$text
ForegroundPositive=$green
ForegroundVisited=$mauve

[Colors:View]
BackgroundAlternate=$win_alt
BackgroundNormal=$win
DecorationFocus=$accent
DecorationHover=$surf0
ForegroundActive=$accent
ForegroundInactive=$ov0
ForegroundLink=$blue
ForegroundNegative=$red
ForegroundNeutral=$yellow
ForegroundNormal=$text
ForegroundPositive=$green
ForegroundVisited=$mauve

[Colors:Window]
BackgroundAlternate=$win_alt
BackgroundNormal=$win
DecorationFocus=$accent
DecorationHover=$surf0
ForegroundActive=$accent
ForegroundInactive=$ov0
ForegroundLink=$blue
ForegroundNegative=$red
ForegroundNeutral=$yellow
ForegroundNormal=$text
ForegroundPositive=$green
ForegroundVisited=$mauve

[General]
ColorScheme=Quickshell
Name=Quickshell

[KDE]
contrast=4
EOF

  # Copy as a .colors file so KDE apps (Kdenlive etc.) can reference it by name
  local colors_dir="$HOME/.local/share/color-schemes"
  mkdir -p "$colors_dir"
  cp "$HOME/.config/kdeglobals" "$colors_dir/Quickshell.colors"

  # Update kdenliverc if present
  local kdenliverc="$HOME/.config/kdenliverc"
  if [ -f "$kdenliverc" ]; then
    sed -i \
      -e "s|^ColorScheme=.*|ColorScheme=Quickshell|" \
      -e "s|^ColorSchemePath=.*|ColorSchemePath=$colors_dir/Quickshell.colors|" \
      "$kdenliverc"
  fi
}

# ── GIMP ────────────────────────────────────────────────────────────────────
gen_gimp_theme() {
  local gimp_css="$HOME/.config/GIMP/3.0/gimp.css"
  cat > "$gimp_css" << EOF
@define-color fg-color               ${C[text]};
@define-color bg-color               ${C[base]};
@define-color border-color           ${C[crust]};
@define-color dimmed-fg-color        ${C[subtext0]};
@define-color disabled-fg-color      ${C[overlay1]};
@define-color disabled-button-color  ${C[overlay0]};
@define-color hover-color            ${C[surface1]};
@define-color widget-bg-color        ${C[mantle]};
@define-color selected-color         ${C[surface0]};
@define-color extreme-bg-color       ${C[crust]};
@define-color extreme-selected-color ${C[surface0]};
@define-color strong-border-color    ${C[mantle]};
@define-color stronger-border-color  ${C[surface1]};
@define-color edge-border-color      ${C[crust]};
@define-color scrollbar-slider-color ${C[overlay1]};
@define-color scrollbar-trough-color ${C[base]};
EOF
}

# ── Main ────────────────────────────────────────────────────────────────────
switch_kitty
gen_btop_theme
gen_yazi_theme
gen_swaync_style
nvim_reload
switch_gtk
switch_qt
live_reload
switch_wallpaper
gen_fastfetch_config
switch_cider
switch_vesktop
switch_steam
switch_obs
switch_librewolf
gen_userstyles
switch_jellyfin
switch_obsidian
switch_gdu
switch_aerc
switch_blender
gen_kdeglobals
gen_hyprlock_theme
gen_gimp_theme

echo "Switched theme to: ${C[name]}"
