switch_discord() {
  local theme_file="$HOME/.config/Vencord/themes/quickshell-theme.css"
  local assets_dir="$SCRIPT_DIR/discord"
  mkdir -p "$(dirname "$theme_file")"

  # Detect shell mode
  local shell_mode="modern"
  local shell_file="$HOME/.config/quickshell/.current-shell"
  if [ -f "$shell_file" ]; then
    shell_mode="$(tr -d '[:space:]' < "$shell_file")"
  fi

  # Build CSS base
  {
    cat << EOF
/**
 * @name quickshell-${shell_mode}
 * @description ${C[name]} — auto-generated by switch-theme.sh
 * @author quickshell
 * @version 1.0.0
 */

EOF

    if [ "$shell_mode" = "tui" ]; then
      # Keep the existing Midnight + System24 stack for the TUI shell.
      cat "$assets_dir/midnight-build.css"
      cat "$assets_dir/system24-build.css"

      cat << EOF

/* === Quickshell Layout & Font Overrides === */
body {
    --font: 'IosevkaTerm Nerd Font Mono';
    --code-font: 'IosevkaTerm Nerd Font Mono';
    font-weight: 300;
    letter-spacing: -0.05ch;
    --unrounding: on;
    --panel-labels: on;
    --ascii-titles: on;
    --ascii-loader: system24;
    --custom-spotify-bar: on;
    --custom-window-controls: off;
    --custom-dms-icon: off;
    --custom-chatbar: separated;
    --chatbar-height: 56px;
    --small-user-panel: on;
    --animations: on;
}

/* === Quickshell Color Overrides === */
:root {
    --colors: on;

    /* text colors */
    --text-0: ${C[crust]};
    --text-1: ${C[text]};
    --text-2: ${C[text]};
    --text-3: ${C[subtext1]};
    --text-4: ${C[subtext0]};
    --text-5: ${C[overlay1]};

    /* background and dark colors */
    --bg-1: ${C[surface1]};
    --bg-2: ${C[surface0]};
    --bg-3: ${C[mantle]};
    --bg-4: ${C[base]};
    --hover: ${C[overlay0]}1a;
    --active: ${C[overlay0]}33;
    --active-2: ${C[overlay0]}4d;
    --message-hover: ${C[overlay0]}1a;

    /* accent colors */
    --accent-1: ${C[accent]};
    --accent-2: ${C[accent]};
    --accent-3: ${C[accent]};
    --accent-4: ${C[accent]};
    --accent-5: ${C[accent]};
    --accent-new: ${C[red]};
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 95%) 40%, transparent);

    /* status indicator colors */
    --online: ${C[green]};
    --dnd: ${C[red]};
    --idle: ${C[yellow]};
    --streaming: ${C[mauve]};
    --offline: ${C[subtext0]};

    /* border colors */
    --border-light: ${C[overlay0]}1a;
    --border: ${C[overlay0]}33;
    --border-hover: var(--accent-2);
    --button-border: ${C[overlay0]}1a;

    /* base colors */
    --red-1: ${C[red]};
    --red-2: ${C[red]};
    --red-3: ${C[red]};
    --red-4: ${C[red]};
    --red-5: ${C[red]};

    --green-1: ${C[green]};
    --green-2: ${C[green]};
    --green-3: ${C[green]};
    --green-4: ${C[green]};
    --green-5: ${C[green]};

    --blue-1: ${C[blue]};
    --blue-2: ${C[blue]};
    --blue-3: ${C[blue]};
    --blue-4: ${C[blue]};
    --blue-5: ${C[blue]};

    --yellow-1: ${C[yellow]};
    --yellow-2: ${C[yellow]};
    --yellow-3: ${C[yellow]};
    --yellow-4: ${C[yellow]};
    --yellow-5: ${C[yellow]};

    --purple-1: ${C[mauve]};
    --purple-2: ${C[mauve]};
    --purple-3: ${C[mauve]};
    --purple-4: ${C[mauve]};
    --purple-5: ${C[mauve]};
}
EOF
    else
      cat << EOF
@import url("https://catppuccin.github.io/discord/dist/catppuccin-mocha.theme.css");

/* Catppuccin layout with the active Quickshell palette. */
.visual-refresh.theme-dark,
.visual-refresh .theme-dark,
.visual-refresh.theme-light,
.visual-refresh .theme-light {
    --font-primary: 'JetBrainsMono Nerd Font';
    --font-display: 'JetBrainsMono Nerd Font';
    --font-headline: 'JetBrainsMono Nerd Font';
    --font-code: 'JetBrainsMono Nerd Font';

    --brand-100: color-mix(in srgb, ${C[accent]} 10%, white) !important;
    --brand-130: color-mix(in srgb, ${C[accent]} 15%, white) !important;
    --brand-160: color-mix(in srgb, ${C[accent]} 20%, white) !important;
    --brand-200: color-mix(in srgb, ${C[accent]} 25%, white) !important;
    --brand-230: color-mix(in srgb, ${C[accent]} 30%, white) !important;
    --brand-260: color-mix(in srgb, ${C[accent]} 35%, white) !important;
    --brand-300: color-mix(in srgb, ${C[accent]} 40%, white) !important;
    --brand-330: color-mix(in srgb, ${C[accent]} 50%, white) !important;
    --brand-360: color-mix(in srgb, ${C[accent]} 60%, white) !important;
    --brand-400: color-mix(in srgb, ${C[accent]} 70%, white) !important;
    --brand-430: color-mix(in srgb, ${C[accent]} 80%, white) !important;
    --brand-460: color-mix(in srgb, ${C[accent]} 90%, white) !important;
    --brand-500: ${C[accent]} !important;
    --brand-530: color-mix(in srgb, ${C[accent]} 95%, black) !important;
    --brand-560: color-mix(in srgb, ${C[accent]} 90%, black) !important;
    --brand-600: color-mix(in srgb, ${C[accent]} 85%, black) !important;
    --brand-630: color-mix(in srgb, ${C[accent]} 80%, black) !important;
    --brand-660: color-mix(in srgb, ${C[accent]} 75%, black) !important;
    --brand-700: color-mix(in srgb, ${C[accent]} 70%, black) !important;
    --brand-730: color-mix(in srgb, ${C[accent]} 65%, black) !important;
    --brand-760: color-mix(in srgb, ${C[accent]} 60%, black) !important;
    --brand-800: color-mix(in srgb, ${C[accent]} 55%, black) !important;
    --brand-830: color-mix(in srgb, ${C[accent]} 50%, black) !important;
    --brand-860: color-mix(in srgb, ${C[accent]} 45%, black) !important;
    --brand-900: color-mix(in srgb, ${C[accent]} 40%, black) !important;

    --brand-05a: color-mix(in srgb, ${C[accent]} 5%, transparent) !important;
    --brand-10a: color-mix(in srgb, ${C[accent]} 10%, transparent) !important;
    --brand-15a: color-mix(in srgb, ${C[accent]} 15%, transparent) !important;
    --brand-20a: color-mix(in srgb, ${C[accent]} 20%, transparent) !important;
    --brand-25a: color-mix(in srgb, ${C[accent]} 25%, transparent) !important;
    --brand-30a: color-mix(in srgb, ${C[accent]} 30%, transparent) !important;
    --brand-35a: color-mix(in srgb, ${C[accent]} 35%, transparent) !important;
    --brand-40a: color-mix(in srgb, ${C[accent]} 40%, transparent) !important;
    --brand-45a: color-mix(in srgb, ${C[accent]} 45%, transparent) !important;
    --brand-50a: color-mix(in srgb, ${C[accent]} 50%, transparent) !important;
    --brand-55a: color-mix(in srgb, ${C[accent]} 55%, transparent) !important;
    --brand-60a: color-mix(in srgb, ${C[accent]} 60%, transparent) !important;
    --brand-65a: color-mix(in srgb, ${C[accent]} 65%, transparent) !important;
    --brand-70a: color-mix(in srgb, ${C[accent]} 70%, transparent) !important;
    --brand-75a: color-mix(in srgb, ${C[accent]} 75%, transparent) !important;
    --brand-80a: color-mix(in srgb, ${C[accent]} 80%, transparent) !important;
    --brand-85a: color-mix(in srgb, ${C[accent]} 85%, transparent) !important;
    --brand-90a: color-mix(in srgb, ${C[accent]} 90%, transparent) !important;
    --brand-95a: color-mix(in srgb, ${C[accent]} 95%, transparent) !important;

    --__header-bar-background: ${C[mantle]} !important;
    --text-default: ${C[text]} !important;
    --text-muted: ${C[subtext0]} !important;
    --text-link: ${C[blue]} !important;
    --text-brand: ${C[accent]} !important;
    --text-strong: ${C[text]} !important;
    --text-subtle: ${C[subtext1]} !important;
    --text-feedback-positive: ${C[green]} !important;
    --text-feedback-critical: ${C[red]} !important;
    --text-feedback-warning: ${C[yellow]} !important;
    --text-feedback-info: ${C[blue]} !important;
    --message-reacted-background-default: color-mix(in srgb, ${C[accent]} 30%, transparent) !important;
    --message-reacted-text-default: ${C[accent]} !important;
    --opacity-blurple-8: color-mix(in srgb, ${C[accent]} 8%, transparent) !important;
    --opacity-blurple-16: color-mix(in srgb, ${C[accent]} 16%, transparent) !important;
    --opacity-blurple-24: color-mix(in srgb, ${C[accent]} 24%, transparent) !important;
    --opacity-blurple-32: color-mix(in srgb, ${C[accent]} 32%, transparent) !important;
    --opacity-blurple-60: color-mix(in srgb, ${C[accent]} 60%, transparent) !important;
    --blurple-50: ${C[accent]} !important;
    --blurple-60: color-mix(in srgb, ${C[accent]} 90%, black) !important;

    --app-frame-background: ${C[crust]} !important;
    --background-secondary-alt: ${C[base]} !important;
    --background-accent: ${C[surface1]} !important;
    --background-surface-highest: ${C[surface0]} !important;
    --background-surface-higher: ${C[mantle]} !important;
    --background-surface-high: ${C[base]} !important;
    --background-base-lowest: ${C[crust]} !important;
    --background-base-lower: ${C[mantle]} !important;
    --background-base-low: ${C[base]} !important;
    --bg-surface-raised: ${C[mantle]} !important;
    --background-gradient-highest: ${C[base]} !important;
    --home-background: ${C[base]} !important;
    --chat-background: ${C[base]} !important;
    --chat-background-default: ${C[base]} !important;
    --chat-border: ${C[crust]} !important;
    --chat-text-muted: ${C[subtext0]} !important;
    --checkbox-icon-active: ${C[crust]} !important;
    --checkbox-border-default: ${C[overlay0]} !important;
    --radio-thumb-background-active: ${C[crust]} !important;
    --border-muted: ${C[surface0]} !important;
    --border-strong: ${C[mantle]} !important;
    --border-normal: ${C[crust]} !important;
    --border-subtle: ${C[base]} !important;
    --background-mod-muted: color-mix(in srgb, ${C[surface2]} 5%, transparent) !important;
    --background-mod-normal: color-mix(in srgb, ${C[surface2]} 15%, transparent) !important;
    --background-mod-subtle: color-mix(in srgb, ${C[surface2]} 25%, transparent) !important;
    --background-mod-strong: color-mix(in srgb, ${C[surface2]} 45%, transparent) !important;
    --custom-channel-members-bg: ${C[mantle]} !important;
    --custom-status-bubble-background: ${C[crust]} !important;
    --custom-status-bubble-background-color: ${C[mantle]} !important;
    --card-background-default: ${C[surface0]} !important;

    --background-feedback-positive: color-mix(in srgb, ${C[green]} 15%, transparent) !important;
    --icon-feedback-positive: ${C[green]} !important;
    --background-feedback-warning: color-mix(in srgb, ${C[yellow]} 15%, transparent) !important;
    --icon-feedback-warning: ${C[yellow]} !important;
    --background-feedback-critical: color-mix(in srgb, ${C[red]} 15%, transparent) !important;
    --icon-feedback-critical: ${C[red]} !important;
    --background-feedback-info: color-mix(in srgb, ${C[sky]} 15%, transparent) !important;
    --icon-feedback-info: ${C[sky]} !important;
    --background-feedback-notification: ${C[red]} !important;
    --icon-feedback-notification: ${C[red]} !important;
    --badge-notification-background: ${C[red]} !important;
    --status-positive: ${C[green]} !important;
    --status-positive-background: ${C[green]} !important;
    --status-positive-text: ${C[base]} !important;
    --status-warning: ${C[yellow]} !important;
    --status-warning-background: ${C[yellow]} !important;
    --status-warning-text: ${C[base]} !important;
    --status-danger: ${C[red]} !important;

    --black-500: ${C[crust]} !important;
    --green-300: ${C[green]} !important;
    --green-360: ${C[green]} !important;
    --yellow-300: ${C[yellow]} !important;
    --yellow-360: ${C[yellow]} !important;
    --red-400: ${C[red]} !important;
    --red-430: ${C[red]} !important;
    --red-500: ${C[maroon]} !important;
    --blue-500: ${C[blue]} !important;
    --blue-530: ${C[sapphire]} !important;
    --primary-100: ${C[subtext1]} !important;
    --primary-200: ${C[subtext0]} !important;
    --primary-300: ${C[subtext1]} !important;
    --primary-400: ${C[subtext1]} !important;
    --primary-630: ${C[surface0]} !important;
    --primary-700: ${C[surface1]} !important;
    --primary-800: ${C[crust]} !important;
    --white: ${C[text]} !important;
    --white-500: ${C[text]} !important;

    --guild-boosting-pink: ${C[pink]} !important;
    --guild-boosting-blue: ${C[blue]} !important;
    --guild-boosting-purple: ${C[mauve]} !important;
    --premium-perk-yellow: ${C[yellow]} !important;
    --premium-perk-purple: ${C[mauve]} !important;
    --premium-perk-dark-blue: ${C[blue]} !important;
    --premium-perk-light-blue: ${C[sky]} !important;
    --premium-perk-blue: ${C[blue]} !important;
    --premium-perk-green: ${C[green]} !important;
    --premium-perk-pink: ${C[pink]} !important;
    --premium-perk-orange: ${C[peach]} !important;
    --premium-tier-0-blue: ${C[blue]} !important;
    --premium-tier-0-purple: ${C[mauve]} !important;
    --premium-tier-1-blue-for-gradients: ${C[sapphire]} !important;
    --premium-tier-1-dark-blue-for-gradients: ${C[blue]} !important;
    --premium-tier-2-purple-for-gradients: ${C[mauve]} !important;
    --premium-tier-2-purple-for-gradients-2: ${C[mauve]} !important;
    --premium-tier-2-pink-for-gradients: ${C[pink]} !important;

    --control-primary-background-default: ${C[accent]} !important;
    --control-primary-background-hover: color-mix(in srgb, ${C[accent]} 92%, black) !important;
    --control-primary-background-active: color-mix(in srgb, ${C[accent]} 87%, black) !important;
    --control-secondary-background-default: ${C[surface1]} !important;
    --control-secondary-background-hover: color-mix(in srgb, ${C[surface1]} 95%, black) !important;
    --control-secondary-background-active: color-mix(in srgb, ${C[surface1]} 92%, black) !important;
    --control-secondary-border-default: ${C[surface0]} !important;
}
EOF
    fi
  } > "$theme_file"
  enable_vencord_theme "$HOME/.config/Vencord/settings/settings.json"
}

enable_vencord_theme() {
  local settings_file="$1"
  local theme_name="quickshell-theme.css"

  [ -f "$settings_file" ] || return 0
  command -v perl >/dev/null 2>&1 || return 0

  local tmp_file
  tmp_file="$(mktemp)"

  if THEME_NAME="$theme_name" perl -0 -pe '
    my $theme = $ENV{THEME_NAME};
    if (!/"enabledThemes"\s*:\s*\[[^\]]*"\Q$theme\E"[^\]]*\]/s) {
      s/("enabledThemes"\s*:\s*\[\s*)(\])/$1\n        "$theme"\n    $2/s
        or s/("enabledThemes"\s*:\s*\[)(.*?)(\s*\])/$1$2,\n        "$theme"$3/s;
    }
  ' "$settings_file" > "$tmp_file"; then
    mv "$tmp_file" "$settings_file"
  else
    rm -f "$tmp_file"
  fi
}
