switch_obsidian() {
  local registry="$HOME/.config/obsidian/obsidian.json"
  [ -f "$registry" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  local base_hex="${C[base]#\#}"
  local text_hex="${C[text]#\#}"
  local base_sum=$(( 0x${base_hex:0:2} + 0x${base_hex:2:2} + 0x${base_hex:4:2} ))
  local text_sum=$(( 0x${text_hex:0:2} + 0x${text_hex:2:2} + 0x${text_hex:4:2} ))
  local color_scheme="dark"
  local on_accent="${C[crust]}"
  if [ "$base_sum" -gt "$text_sum" ]; then
    color_scheme="light"
    on_accent="${C[text]}"
  fi

  local vault appearance snippets_dir snippet appearance_tmp
  while IFS= read -r vault; do
    [ -d "$vault/.obsidian" ] || continue
    appearance="$vault/.obsidian/appearance.json"
    snippets_dir="$vault/.obsidian/snippets"
    snippet="$snippets_dir/quickshell.css"
    mkdir -p "$snippets_dir"

    cat > "$snippet" << EOF
/* Quickshell theme — auto-generated by switch-theme.sh */
.theme-dark,
.theme-light {
  color-scheme: $color_scheme;

  --color-base-00: ${C[base]};
  --color-base-05: ${C[base]};
  --color-base-10: ${C[mantle]};
  --color-base-20: ${C[surface0]};
  --color-base-25: ${C[surface0]};
  --color-base-30: ${C[surface1]};
  --color-base-35: ${C[surface2]};
  --color-base-40: ${C[overlay0]};
  --color-base-50: ${C[overlay1]};
  --color-base-60: ${C[subtext0]};
  --color-base-70: ${C[subtext1]};
  --color-base-100: ${C[text]};

  --color-red: ${C[red]};
  --color-orange: ${C[peach]};
  --color-yellow: ${C[yellow]};
  --color-green: ${C[green]};
  --color-cyan: ${C[teal]};
  --color-blue: ${C[blue]};
  --color-purple: ${C[mauve]};
  --color-pink: ${C[pink]};
  --color-accent: ${C[accent]};
  --color-accent-1: ${C[mauve]};
  --color-accent-2: ${C[blue]};

  --background-primary: ${C[base]};
  --background-primary-alt: ${C[mantle]};
  --background-secondary: ${C[mantle]};
  --background-secondary-alt: ${C[crust]};
  --background-modifier-hover: ${C[surface0]};
  --background-modifier-active-hover: ${C[surface1]};
  --background-modifier-border: ${C[surface1]};
  --background-modifier-border-hover: ${C[overlay0]};
  --background-modifier-border-focus: ${C[accent]};
  --background-modifier-form-field: ${C[surface0]};
  --background-modifier-error: ${C[red]};
  --background-modifier-success: ${C[green]};
  --background-modifier-message: ${C[mantle]};

  --interactive-normal: ${C[surface0]};
  --interactive-hover: ${C[surface1]};
  --interactive-accent: ${C[accent]};
  --interactive-accent-hover: ${C[mauve]};

  --text-normal: ${C[text]};
  --text-muted: ${C[subtext0]};
  --text-faint: ${C[overlay0]};
  --text-on-accent: $on_accent;
  --text-on-accent-inverted: $on_accent;
  --text-success: ${C[green]};
  --text-warning: ${C[yellow]};
  --text-error: ${C[red]};
  --text-accent: ${C[accent]};
  --text-accent-hover: ${C[mauve]};
  --text-selection: color-mix(in oklch, ${C[accent]} 35%, transparent);
  --text-highlight-bg: color-mix(in oklch, ${C[yellow]} 35%, transparent);
  --caret-color: ${C[accent]};

  --divider-color: ${C[surface1]};
  --icon-color: ${C[subtext0]};
  --icon-color-hover: ${C[text]};
  --icon-color-active: ${C[accent]};
  --icon-color-focused: ${C[accent]};
  --titlebar-background: ${C[mantle]};
  --titlebar-background-focused: ${C[mantle]};
  --tab-container-background: ${C[mantle]};
  --tab-background-active: ${C[base]};
  --tab-outline-color: ${C[surface1]};
  --modal-background: ${C[base]};
  --modal-border-color: ${C[surface1]};
  --code-background: ${C[mantle]};
  --code-normal: ${C[text]};
  --blockquote-border-color: ${C[accent]};
  --checkbox-color: ${C[accent]};
  --checkbox-color-hover: ${C[mauve]};
  --checkbox-marker-color: $on_accent;
  --canvas-background: ${C[base]};
}
EOF

    [ -f "$appearance" ] || printf '{}\n' > "$appearance"
    appearance_tmp="$(mktemp "${appearance}.XXXXXX")" || continue
    if jq '
      (if (.enabledCssSnippets | type) == "array" then .enabledCssSnippets else [] end) as $snippets
      | .enabledCssSnippets = (
          if ($snippets | index("quickshell")) == null
          then $snippets + ["quickshell"]
          else $snippets
          end
        )
    ' "$appearance" > "$appearance_tmp"; then
      mv "$appearance_tmp" "$appearance"
    else
      rm -f "$appearance_tmp"
    fi
  done < <(jq -r '.vaults // {} | .[] | .path // empty' "$registry")
}
