switch_swaync() {
  mkdir -p "$HOME/.config/swaync"
  cat > "$HOME/.config/swaync/style.css" << EOF
/* ${C[name]} — auto-generated by switch-theme.sh */
* {
  all: unset;
  font-size: 14px;
  font-family: "JetBrainsMono Nerd Font";
  transition: 200ms;
}

trough highlight { background: ${C[text]}; }

scale { margin: 0 7px; }

scale trough {
  margin: 0rem 1rem;
  min-height: 8px;
  min-width: 70px;
  border-radius: 12.6px;
}

trough slider {
  margin: -10px;
  border-radius: 12.6px;
  box-shadow: 0 0 2px rgba(0,0,0,0.8);
  transition: all 0.2s ease;
  background-color: ${C[blue]};
}

trough slider:hover {
  box-shadow: 0 0 2px rgba(0,0,0,0.8), 0 0 8px ${C[blue]};
}

trough { background-color: ${C[surface0]}; }

.notification-background {
  box-shadow: 0 0 8px 0 rgba(0,0,0,0.8), inset 0 0 0 1px ${C[surface1]};
  border-radius: 12.6px;
  margin: 18px;
  background: ${C[mantle]};
  color: ${C[text]};
  padding: 0;
}

.notification-background .notification {
  padding: 7px;
  border-radius: 12.6px;
}

.notification-background .notification.critical {
  box-shadow: inset 0 0 7px 0 ${C[red]};
}

.notification .notification-content { margin: 7px; }
.notification .notification-content overlay { margin: 4px; }

.notification-content .summary { color: ${C[text]}; }
.notification-content .time    { color: ${C[subtext0]}; }
.notification-content .body    { color: ${C[subtext1]}; }

.notification > *:last-child > * { min-height: 3.4em; }

.notification-background .close-button {
  margin: 7px;
  padding: 2px;
  border-radius: 6.3px;
  color: ${C[base]};
  background-color: ${C[red]};
}

.notification-background .close-button:hover  { background-color: ${C[maroon]}; }
.notification-background .close-button:active { background-color: ${C[pink]}; }

.notification .notification-action {
  border-radius: 7px;
  color: ${C[text]};
  box-shadow: inset 0 0 0 1px ${C[surface1]};
  margin: 4px;
  padding: 8px;
  background-color: ${C[surface0]};
}

.notification .notification-action:hover  { background-color: ${C[surface1]}; }
.notification .notification-action:active { background-color: ${C[surface2]}; }

.notification.critical progress { background-color: ${C[red]}; }
.notification.low progress,
.notification.normal progress   { background-color: ${C[blue]}; }

.notification progress,
.notification trough,
.notification progressbar {
  border-radius: 12.6px;
  padding: 3px 0;
}

.control-center {
  box-shadow: 0 0 8px 0 rgba(0,0,0,0.8), inset 0 0 0 1px ${C[surface0]};
  border-radius: 12.6px;
  background-color: ${C[base]};
  color: ${C[text]};
  padding: 14px;
}

.control-center .notification-background {
  border-radius: 7px;
  box-shadow: inset 0 0 0 1px ${C[surface1]};
  margin: 4px 10px;
}

.control-center .notification-background .notification {
  border-radius: 7px;
}

.control-center .notification-background .notification.low { opacity: 0.8; }

.control-center .widget-title > label {
  color: ${C[text]};
  font-size: 1.3em;
}

.control-center .widget-title button {
  border-radius: 7px;
  color: ${C[text]};
  background-color: ${C[surface0]};
  box-shadow: inset 0 0 0 1px ${C[surface1]};
  padding: 8px;
}

.control-center .widget-title button:hover  { background-color: ${C[surface1]}; }
.control-center .widget-title button:active { background-color: ${C[surface2]}; }

.control-center .notification-group { margin-top: 10px; }

.control-center .notification-group:focus .notification-background {
  background-color: ${C[surface0]};
}

scrollbar slider { margin: -3px; opacity: 0.8; }
scrollbar trough { margin: 2px 0; }

.widget-dnd {
  margin-top: 5px;
  border-radius: 8px;
  font-size: 1.1rem;
}

.widget-dnd > switch {
  font-size: initial;
  border-radius: 8px;
  background: ${C[surface0]};
  box-shadow: none;
}

.widget-dnd > switch:checked { background: ${C[blue]}; }

.widget-dnd > switch slider {
  background: ${C[surface1]};
  border-radius: 8px;
}

.widget-mpris-player {
  background: ${C[surface0]};
  border-radius: 12.6px;
  color: ${C[text]};
}

.mpris-overlay {
  background-color: ${C[surface0]};
  opacity: 0.9;
  padding: 15px 10px;
}

.widget-mpris-album-art {
  -gtk-icon-size: 100px;
  border-radius: 12.6px;
  margin: 0 10px;
}

.widget-mpris-title    { font-size: 1.2rem; color: ${C[text]}; }
.widget-mpris-subtitle { font-size: 1rem;   color: ${C[subtext1]}; }

.widget-mpris button {
  border-radius: 12.6px;
  color: ${C[text]};
  margin: 0 5px;
  padding: 2px;
}

.widget-mpris button image    { -gtk-icon-size: 1.8rem; }
.widget-mpris button:hover    { background-color: ${C[surface0]}; }
.widget-mpris button:active   { background-color: ${C[surface1]}; }
.widget-mpris button:disabled { opacity: 0.5; }

.widget-volume { padding: 1rem 0; }

.widget-volume label {
  color: ${C[sapphire]};
  padding: 0 1rem;
}

.widget-volume trough highlight   { background: ${C[sapphire]}; }
.widget-backlight trough highlight { background: ${C[yellow]}; }

.widget-backlight label {
  font-size: 1.5rem;
  color: ${C[yellow]};
}

.widget-backlight .KB { padding-bottom: 1rem; }

.image { padding-right: 0.5rem; }
EOF

  swaync-client -rs 2>/dev/null || true
}
