switch_alacritty() {
  mkdir -p "$HOME/.config/alacritty"
  cat > "$HOME/.config/alacritty/theme.toml" << EOF
# ${C[name]} — auto-generated by switch-theme.sh
[colors.primary]
foreground = "${C[text]}"
background = "${C[base]}"

[colors.cursor]
text = "${C[base]}"
cursor = "${C[rosewater]}"

[colors.selection]
text = "${C[base]}"
background = "${C[rosewater]}"

[colors.normal]
black = "${C[surface1]}"
red = "${C[red]}"
green = "${C[green]}"
yellow = "${C[yellow]}"
blue = "${C[blue]}"
magenta = "${C[pink]}"
cyan = "${C[teal]}"
white = "${C[subtext1]}"

[colors.bright]
black = "${C[surface2]}"
red = "${C[red]}"
green = "${C[green]}"
yellow = "${C[yellow]}"
blue = "${C[blue]}"
magenta = "${C[pink]}"
cyan = "${C[teal]}"
white = "${C[subtext0]}"
EOF
}
