switch_btop() {
  local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/btop"
  local config="$config_dir/btop.conf"
  local theme_dir="$config_dir/themes"
  local theme="$theme_dir/quickshell.theme"

  mkdir -p "$theme_dir"

  cat > "$theme" << EOF
# ${C[name]} - auto-generated by switch-theme.sh
theme[main_bg]="${C[base]}"
theme[main_fg]="${C[text]}"
theme[title]="${C[text]}"
theme[hi_fg]="${C[accent]}"
theme[selected_bg]="${C[surface1]}"
theme[selected_fg]="${C[accent]}"
theme[inactive_fg]="${C[overlay0]}"
theme[graph_text]="${C[rosewater]}"
theme[meter_bg]="${C[surface1]}"
theme[proc_misc]="${C[rosewater]}"
theme[cpu_box]="${C[mauve]}"
theme[mem_box]="${C[green]}"
theme[net_box]="${C[maroon]}"
theme[proc_box]="${C[blue]}"
theme[div_line]="${C[overlay0]}"
theme[temp_start]="${C[green]}"
theme[temp_mid]="${C[yellow]}"
theme[temp_end]="${C[red]}"
theme[cpu_start]="${C[teal]}"
theme[cpu_mid]="${C[sky]}"
theme[cpu_end]="${C[lavender]}"
theme[free_start]="${C[mauve]}"
theme[free_mid]="${C[lavender]}"
theme[free_end]="${C[blue]}"
theme[cached_start]="${C[sapphire]}"
theme[cached_mid]="${C[blue]}"
theme[cached_end]="${C[lavender]}"
theme[available_start]="${C[peach]}"
theme[available_mid]="${C[maroon]}"
theme[available_end]="${C[red]}"
theme[used_start]="${C[green]}"
theme[used_mid]="${C[teal]}"
theme[used_end]="${C[sky]}"
theme[download_start]="${C[peach]}"
theme[download_mid]="${C[maroon]}"
theme[download_end]="${C[red]}"
theme[upload_start]="${C[green]}"
theme[upload_mid]="${C[teal]}"
theme[upload_end]="${C[sky]}"
theme[process_start]="${C[sapphire]}"
theme[process_mid]="${C[lavender]}"
theme[process_end]="${C[mauve]}"
EOF

  [ -f "$config" ] || return 0

  local tmp
  tmp="$(mktemp "$config.XXXXXX")" || return 0
  if grep -q '^[[:space:]]*color_theme[[:space:]]*=' "$config"; then
    sed 's/^[[:space:]]*color_theme[[:space:]]*=.*/color_theme = "quickshell"/' "$config" > "$tmp"
  else
    cp "$config" "$tmp"
    printf '\ncolor_theme = "quickshell"\n' >> "$tmp"
  fi
  mv "$tmp" "$config"

  pkill -USR2 -x btop 2>/dev/null || true
}
