switch_discord() {
  local theme_file="$HOME/.config/Vencord/themes/quickshell-theme.css"
  local assets_dir="$SCRIPT_DIR/discord"
  mkdir -p "$(dirname "$theme_file")"

  # Detect shell mode
  local shell_mode="modern"
  local shell_file="$HOME/.config/quickshell/.current-shell"
  if [ -f "$shell_file" ]; then
    shell_mode="$(tr -d '[:space:]' < "$shell_file")"
  fi

  # Build CSS base
  {
    cat << EOF
/**
 * @name quickshell-${shell_mode}
 * @description ${C[name]} — auto-generated by switch-theme.sh
 * @author quickshell
 * @version 1.0.0
 */

EOF

    # Base build: midnight is always included
    cat "$assets_dir/midnight-build.css"

    # System24 overrides for TUI mode
    if [ "$shell_mode" = "tui" ]; then
      cat "$assets_dir/system24-build.css"
    fi

    # Layout and font overrides
    cat << EOF

/* === Quickshell Layout & Font Overrides === */
body {
EOF

    if [ "$shell_mode" = "tui" ]; then
      cat << EOF
    --font: 'IosevkaTerm Nerd Font Mono';
    --code-font: 'IosevkaTerm Nerd Font Mono';
    font-weight: 300;
    letter-spacing: -0.05ch;
    --unrounding: on;
    --panel-labels: on;
    --ascii-titles: on;
    --ascii-loader: system24;
    --custom-spotify-bar: on;
    --custom-window-controls: off;
    --custom-dms-icon: off;
    --custom-chatbar: separated;
    --chatbar-height: 56px;
EOF
    else
      cat << EOF
    --font: 'JetBrainsMono Nerd Font';
    --code-font: 'JetBrainsMono Nerd Font';
    font-weight: 400;
    letter-spacing: normal;
    --unrounding: off;
    --panel-labels: off;
    --ascii-titles: off;
    --ascii-loader: off;
    --custom-spotify-bar: off;
    --custom-window-controls: off;
    --custom-dms-icon: custom;
    --dms-icon-svg-url: url('https://refact0r.github.io/midnight-discord/assets/Font_Awesome_5_solid_moon.svg');
    --custom-chatbar: off;
    --chatbar-height: 47px;
EOF
    fi

    cat << EOF
    --small-user-panel: on;
    --animations: on;
}

/* === Quickshell Color Overrides === */
:root {
    --colors: on;

    /* text colors */
    --text-0: ${C[crust]};
    --text-1: ${C[text]};
    --text-2: ${C[text]};
    --text-3: ${C[subtext1]};
    --text-4: ${C[subtext0]};
    --text-5: ${C[overlay1]};

    /* background and dark colors */
    --bg-1: ${C[surface1]};
    --bg-2: ${C[surface0]};
    --bg-3: ${C[mantle]};
    --bg-4: ${C[base]};
    --hover: ${C[overlay0]}1a;
    --active: ${C[overlay0]}33;
    --active-2: ${C[overlay0]}4d;
    --message-hover: ${C[overlay0]}1a;

    /* accent colors */
    --accent-1: ${C[accent]};
    --accent-2: ${C[accent]};
    --accent-3: ${C[accent]};
    --accent-4: ${C[accent]};
    --accent-5: ${C[accent]};
    --accent-new: ${C[red]};
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 95%) 40%, transparent);

    /* status indicator colors */
    --online: ${C[green]};
    --dnd: ${C[red]};
    --idle: ${C[yellow]};
    --streaming: ${C[mauve]};
    --offline: ${C[subtext0]};

    /* border colors */
    --border-light: ${C[overlay0]}1a;
    --border: ${C[overlay0]}33;
    --border-hover: var(--accent-2);
    --button-border: ${C[overlay0]}1a;

    /* base colors */
    --red-1: ${C[red]};
    --red-2: ${C[red]};
    --red-3: ${C[red]};
    --red-4: ${C[red]};
    --red-5: ${C[red]};

    --green-1: ${C[green]};
    --green-2: ${C[green]};
    --green-3: ${C[green]};
    --green-4: ${C[green]};
    --green-5: ${C[green]};

    --blue-1: ${C[blue]};
    --blue-2: ${C[blue]};
    --blue-3: ${C[blue]};
    --blue-4: ${C[blue]};
    --blue-5: ${C[blue]};

    --yellow-1: ${C[yellow]};
    --yellow-2: ${C[yellow]};
    --yellow-3: ${C[yellow]};
    --yellow-4: ${C[yellow]};
    --yellow-5: ${C[yellow]};

    --purple-1: ${C[mauve]};
    --purple-2: ${C[mauve]};
    --purple-3: ${C[mauve]};
    --purple-4: ${C[mauve]};
    --purple-5: ${C[mauve]};
}
EOF
  } > "$theme_file"
  enable_vencord_theme "$HOME/.config/Vencord/settings/settings.json"
}

enable_vencord_theme() {
  local settings_file="$1"
  local theme_name="quickshell-theme.css"

  [ -f "$settings_file" ] || return 0
  command -v perl >/dev/null 2>&1 || return 0

  local tmp_file
  tmp_file="$(mktemp)"

  if THEME_NAME="$theme_name" perl -0 -pe '
    my $theme = $ENV{THEME_NAME};
    if (!/"enabledThemes"\s*:\s*\[[^\]]*"\Q$theme\E"[^\]]*\]/s) {
      s/("enabledThemes"\s*:\s*\[\s*)(\])/$1\n        "$theme"\n    $2/s
        or s/("enabledThemes"\s*:\s*\[)(.*?)(\s*\])/$1$2,\n        "$theme"$3/s;
    }
  ' "$settings_file" > "$tmp_file"; then
    mv "$tmp_file" "$settings_file"
  else
    rm -f "$tmp_file"
  fi
}
