switch_gdu() {
  local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/gdu"
  mkdir -p "$config_dir"
  cat > "$config_dir/gdu.yaml" << EOF2
# ${C[name]} - auto-generated by switch-theme.sh
style:
  selected-row:
    text-color: "${C[base]}"
    background-color: "${C[accent]}"
  result-row:
    number-color: "${C[yellow]}"
    directory-color: "${C[blue]}"
  header:
    text-color: "${C[text]}"
    background-color: "${C[surface0]}"
  footer:
    text-color: "${C[text]}"
    background-color: "${C[surface0]}"
    number-color: "${C[accent]}"
EOF2
}
