switch_ghostty() {
  mkdir -p "$HOME/.config/ghostty/themes"
  cat > "$HOME/.config/ghostty/themes/current.conf" << EOF
# ${C[name]} - auto-generated by switch-theme.sh
foreground = ${C[text]}
background = ${C[base]}
cursor-color = ${C[rosewater]}
selection-foreground = ${C[base]}
selection-background = ${C[rosewater]}
palette = 0=${C[surface1]}
palette = 1=${C[red]}
palette = 2=${C[green]}
palette = 3=${C[yellow]}
palette = 4=${C[blue]}
palette = 5=${C[pink]}
palette = 6=${C[teal]}
palette = 7=${C[subtext1]}
palette = 8=${C[surface2]}
palette = 9=${C[red]}
palette = 10=${C[green]}
palette = 11=${C[yellow]}
palette = 12=${C[blue]}
palette = 13=${C[pink]}
palette = 14=${C[teal]}
palette = 15=${C[subtext0]}
EOF
}
