switch_heroic() {
  local theme_dir="$HOME/.config/heroic/themes"
  local theme_file="$theme_dir/quickshell.css"
  local settings_file="$HOME/.config/heroic/config.json"
  local config_file="$HOME/.config/heroic/store/config.json"
  mkdir -p "$theme_dir"

  cat > "$theme_file" << EOF
/* Quickshell theme — auto-generated by switch-theme.sh */
body.quickshell {
  --accent: ${C[accent]};
  --accent-overlay: ${C[mauve]};
  --navbar-accent: ${C[accent]};
  --background: ${C[mantle]};
  --background-darker: ${C[crust]};
  --background-darker-80: ${C[crust]}e0;
  --background-lighter: ${C[surface0]};
  --body-background: ${C[base]};
  --current-background: ${C[base]};
  --navbar-background: ${C[mantle]};
  --navbar-active-background: ${C[surface0]};
  --input-background: ${C[surface0]};
  --modal-background: ${C[base]};
  --modal-border: ${C[surface1]};
  --divider: ${C[surface1]};
  --icons-background: ${C[surface0]};
  --primary: ${C[accent]};
  --primary-hover: ${C[mauve]};
  --primary-button: ${C[accent]};
  --secondary-button: ${C[blue]};
  --install-button: ${C[blue]};
  --download-button: ${C[sapphire]};
  --play-button: ${C[green]};
  --success: ${C[green]};
  --success-hover: ${C[teal]};
  --success-button: ${C[green]};
  --danger: ${C[red]};
  --danger-hover: ${C[maroon]};
  --text-title: ${C[text]};
  --text-default: ${C[text]};
  --text-secondary: ${C[subtext1]};
  --text-hover: ${C[accent]};
  --action-icon: ${C[subtext1]};
  --action-icon-hover: ${C[accent]};
  --action-icon-active: ${C[text]};
  --icon-disabled: ${C[overlay0]};
  --gradient-body-background: linear-gradient(
    90deg,
    ${C[crust]} -32px,
    ${C[base]} 64px,
    ${C[base]} 100%
  );
}
EOF

  [ -f "$settings_file" ] && [ -f "$config_file" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  local settings_tmp
  settings_tmp="$(mktemp "${settings_file}.XXXXXX")" || return 0
  if jq --arg theme_dir "$theme_dir" '
    .defaultSettings.customThemesPath = $theme_dir
  ' "$settings_file" > "$settings_tmp"; then
    mv "$settings_tmp" "$settings_file"
  else
    rm -f "$settings_tmp"
    return 0
  fi

  local config_tmp
  config_tmp="$(mktemp "${config_file}.XXXXXX")" || return 0
  if jq --arg theme_dir "$theme_dir" '
    .settings.customThemesPath = $theme_dir
    | .theme = "quickshell.css"
  ' "$config_file" > "$config_tmp"; then
    mv "$config_tmp" "$config_file"
  else
    rm -f "$config_tmp"
  fi
}
