switch_kitty() {
  mkdir -p "$HOME/.config/kitty"
  cat > "$HOME/.config/kitty/theme.conf" << EOF
# ${C[name]} — auto-generated by switch-theme.sh
foreground ${C[text]}
background ${C[base]}
cursor ${C[rosewater]}
cursor_text_color ${C[base]}
selection_foreground ${C[base]}
selection_background ${C[rosewater]}
color0 ${C[surface1]}
color1 ${C[red]}
color2 ${C[green]}
color3 ${C[yellow]}
color4 ${C[blue]}
color5 ${C[pink]}
color6 ${C[teal]}
color7 ${C[subtext1]}
color8 ${C[surface2]}
color9 ${C[red]}
color10 ${C[green]}
color11 ${C[yellow]}
color12 ${C[blue]}
color13 ${C[pink]}
color14 ${C[teal]}
color15 ${C[subtext0]}
EOF
}
