switch_rio() {
  mkdir -p "$HOME/.config/rio/themes"
  cat > "$HOME/.config/rio/themes/switch-theme.toml" << EOF
# ${C[name]} — auto-generated by switch-theme.sh
[colors]
background = "${C[base]}"
foreground = "${C[text]}"
cursor = "${C[rosewater]}"
selection-foreground = "${C[base]}"
selection-background = "${C[rosewater]}"
black = "${C[surface1]}"
red = "${C[red]}"
green = "${C[green]}"
yellow = "${C[yellow]}"
blue = "${C[blue]}"
magenta = "${C[pink]}"
cyan = "${C[teal]}"
white = "${C[subtext1]}"
light-black = "${C[surface2]}"
light-red = "${C[red]}"
light-green = "${C[green]}"
light-yellow = "${C[yellow]}"
light-blue = "${C[blue]}"
light-magenta = "${C[pink]}"
light-cyan = "${C[teal]}"
light-white = "${C[subtext0]}"
EOF
}