switch_steam() {
  local quickcss="$HOME/.config/millennium/quick.css"
  mkdir -p "$(dirname "$quickcss")"

  cat > "$quickcss" << EOF
/* Quickshell theme — auto-generated by switch-theme.sh */
:root {
    --color-light:   ${C[surface1]} !important;
    --color-dark:    ${C[mantle]}   !important;
    --color-darker:  ${C[base]}     !important;
    --color-darkest: ${C[crust]}    !important;
    --scrollbar:     ${C[surface1]} !important;
    --black:         ${C[crust]}    !important;
    --black-ish:     ${C[crust]}    !important;
    --realblack:     ${C[crust]}    !important;
    --blacker-ish:   ${C[crust]}    !important;
    --blacker:       ${C[crust]}    !important;
    --lightblack:    ${C[crust]}    !important;
    --darkergrey:    ${C[crust]}    !important;
    --bedarkgrey:    ${C[crust]}    !important;
    --thegrey:       ${C[mantle]}   !important;
    --begrey:        ${C[surface0]} !important;
    --littlegrey:    ${C[surface0]} !important;
    --darkgrey:      ${C[base]}     !important;
    --grey:          ${C[surface0]} !important;
    --lightgrey:     ${C[surface1]} !important;
    --lightergrey:   ${C[surface0]} !important;
    --grey-ish:      ${C[surface2]} !important;
    --darkerwhite:   ${C[subtext0]} !important;
    --darkwhite:     ${C[subtext1]} !important;
    --white:         ${C[text]}     !important;
    --ingame:        ${C[green]}    !important;
    --online:        ${C[teal]}     !important;
    --offline:       ${C[overlay0]} !important;
}
EOF
}
