gen_userstyles() {
  local cache_dir="$HOME/.config/quickshell/themes/userstyles-cache"
  local compile_js="$HOME/.config/quickshell/themes/compile-userstyle.js"
  local userstyles_css="$HOME/.config/quickshell/themes/userstyles.user.css"

  local gecko_user_contents=()

  local firefox_profiles_ini="$HOME/.config/mozilla/firefox/profiles.ini"
  if [ -f "$firefox_profiles_ini" ]; then
    local firefox_profile_path
    firefox_profile_path=$(awk -F= '/^\[Profile/{path=""; def=0} /^Path=/{path=$2} /^Default=1/{def=1} def && path {print path; exit}' "$firefox_profiles_ini")
    if [ -n "$firefox_profile_path" ]; then
      gecko_user_contents+=("$HOME/.config/mozilla/firefox/$firefox_profile_path/chrome/userContent.css")
    fi
  fi

  local palette
  palette=$(printf '{
    "rosewater":"%s","flamingo":"%s","pink":"%s","mauve":"%s",
    "red":"%s","maroon":"%s","peach":"%s","yellow":"%s",
    "green":"%s","teal":"%s","sky":"%s","sapphire":"%s",
    "blue":"%s","lavender":"%s","text":"%s","subtext1":"%s",
    "subtext0":"%s","overlay2":"%s","overlay1":"%s","overlay0":"%s",
    "surface2":"%s","surface1":"%s","surface0":"%s",
    "base":"%s","mantle":"%s","crust":"%s","accentColor":"%s"
  }' \
    "${C[rosewater]}" "${C[flamingo]}" "${C[pink]}"     "${C[mauve]}"   \
    "${C[red]}"       "${C[maroon]}"   "${C[peach]}"    "${C[yellow]}"  \
    "${C[green]}"     "${C[teal]}"     "${C[sky]}"      "${C[sapphire]}"\
    "${C[blue]}"      "${C[lavender]}" "${C[text]}"     "${C[subtext1]}"\
    "${C[subtext0]}"  "${C[overlay2]}" "${C[overlay1]}" "${C[overlay0]}"\
    "${C[surface2]}"  "${C[surface1]}" "${C[surface0]}"                 \
    "${C[base]}"      "${C[mantle]}"   "${C[crust]}"    "${C[cat_accent]}")

  local gecko_tmp gecko_styles_tmp userstyles_tmp
  gecko_tmp=$(mktemp)
  gecko_styles_tmp=$(mktemp)
  userstyles_tmp=$(mktemp)
  trap 'rm -f "$gecko_tmp" "$gecko_styles_tmp" "$userstyles_tmp"' EXIT

  echo "/* --- userstyles --- */" >> "$gecko_styles_tmp"

  # Helium header — UserCSS format so Stylus can install/auto-update it
  local version
  version=$(date +%Y%m%d%H%M%S)
  cat > "$userstyles_tmp" << EOF
/* ==UserStyle==
@name         Quickshell Theme
@namespace    quickshell.helium
@version      ${version}
@description  Auto-generated by switch-theme.sh - do not edit
@updateURL    http://127.0.0.1:48531/userstyles.user.css
==/UserStyle== */
EOF

  local sites=(twitch twitter instagram reddit github codeberg tuta anilist duckduckgo brave-search wikipedia searxng materialious youtube chatgpt mastodon claude)
  for site in "${sites[@]}"; do
    local less_file="$cache_dir/$site.user.less"
    [ -f "$less_file" ] || continue
    local compiled
    compiled=$(qs-compile-userstyle "$less_file" "$palette" 2>/dev/null) || continue
    echo "/* == $site == */" >> "$userstyles_tmp"
    echo "/* == $site == */" >> "$gecko_styles_tmp"
    printf '%s\n' "$compiled" >> "$userstyles_tmp"
    printf '%s\n' "$compiled" >> "$gecko_styles_tmp"
    if [ "$site" = "claude" ]; then
      (
        claude_css="${XDG_CONFIG_HOME:-$HOME/.config}/claude-desktop/quickshell.css"
        mkdir -p "$(dirname "$claude_css")" && claude_tmp=$(mktemp "${claude_css}.XXXXXX") || exit 1
        trap 'rm -f "$claude_tmp"' EXIT
        qs-compile-userstyle "$less_file" "$palette" --desktop > "$claude_tmp" &&
          mv "$claude_tmp" "$claude_css"
      ) || printf '%s\n' 'Could not update Claude Desktop theme; keeping the previous CSS.' >&2
    fi
  done

  for gecko_user_content in "${gecko_user_contents[@]}"; do
    mkdir -p "$(dirname "$gecko_user_content")"
    : > "$gecko_tmp"
    if [ -f "$gecko_user_content" ]; then
      sed '/^\/\* --- userstyles ---/,$d' "$gecko_user_content" > "$gecko_tmp" 2>/dev/null || cp "$gecko_user_content" "$gecko_tmp"
    fi
    cat "$gecko_styles_tmp" >> "$gecko_tmp"
    cp "$gecko_tmp" "$gecko_user_content"
  done
  mv "$userstyles_tmp" "$userstyles_css"
}
